import { useId, useState, type ReactNode } from 'react';
import { ReviewSectionNav } from '../../../components/ui/workspace';
import { taskEstimateError } from '../../tasks';
import type { DraftTask } from './draftModel';
export function ProposalReviewSections({ tasks, officeCount, scope, work }: { tasks: DraftTask[]; officeCount: number; scope: ReactNode; work: ReactNode }) {
  const prefix = useId(), [selected, setSelected] = useState('work');
  const warnings = tasks.filter(task => task.enabled && (task.assignmentException || task.burnoutWarning || taskEstimateError(task.estimatedHours)));
  const select = (id: string) => { setSelected(id); const target = document.getElementById(prefix + id); target?.scrollIntoView({ block: 'start' }); target?.focus({ preventScroll: true }); };
  return <section aria-label="Work-plan draft review"><p>This persistent draft needs human review and the existing approval/publication workflow. Suggested teams and budget estimates are proposals.</p><ReviewSectionNav selected={selected} onSelect={select} sections={[{id:'scope',label:'Office scope',detail:`${officeCount} participating Offices`},{id:'work',label:'Hierarchy and tasks',detail:`${tasks.filter(task => task.enabled).length} included tasks`},{id:'estimates',label:'Timeline and budget',detail:'Review estimates and source dates'},{id:'warnings',label:'Warnings',detail:`${warnings.length} tasks need attention`}]}/><div id={prefix+'scope'} tabIndex={-1} className="eflow-review-target">{scope}</div><div id={prefix+'estimates'} tabIndex={-1} className="eflow-review-target"><details open={selected==='estimates' ? true : undefined}><summary>Timeline and budget review</summary><ul>{tasks.filter(task => task.enabled).map(task => <li key={task.key}><strong>{task.title}</strong>: {task.deadline || task.activitySchedule || 'No source date'} · {task.estimatedHours ?? 'Unknown'} hours · {(task.budgetLines || []).length} estimate lines · {task.budgetDecision || 'missing'}. Edit estimates in its task row below; these are not authorized or settled funds.</li>)}</ul></details></div><div id={prefix+'warnings'} tabIndex={-1} className="eflow-review-target"><details open={selected==='warnings' ? true : undefined}><summary>Review warnings ({warnings.length})</summary>{warnings.length ? <ul>{warnings.map(task => <li key={task.key}>{task.title}: {taskEstimateError(task.estimatedHours) || (task.burnoutWarning ? 'Review workload before proposing this team.' : 'Review the assignment exception and proposed team in its task row.')}</li>)}</ul> : <p>No task warnings were returned. Review all AI suggestions before approval.</p>}</details></div><div id={prefix+'work'} tabIndex={-1} className="eflow-review-target">{work}</div></section>;
}
