import { expect, test } from "@playwright/test";
import { projectWorkspaceFixture } from "./fixtures/projectWorkspace";
for(const width of [1440,768,390,320]) test(`Admin directory and form preserve authority, associations and pending drafts at ${width}px`,async({page},info)=>{
  test.setTimeout(90_000);await projectWorkspaceFixture(page,"admin");await page.setViewportSize({width,height:900});
  const self=page.getByRole("row").filter({hasText:"Alex Rivera"});await expect(self.getByRole("button",{name:"Delete",exact:true})).toBeDisabled();await expect(self.getByRole("button",{name:"Deactivate",exact:true})).toBeDisabled();
  const scroll=page.getByRole("region",{name:"Scrollable data table"});expect(await scroll.evaluate(el=>getComputedStyle(el).scrollbarWidth)).toBe("thin");await scroll.evaluate(el=>{el.scrollLeft=el.scrollWidth;});
  const member=page.getByRole("row").filter({hasText:"colleague1@example.test"});await member.getByRole("button",{name:"Delete",exact:true}).click();const alert=page.getByRole("alertdialog");await expect(alert).toBeVisible();let deletes=0;await page.route(/\/admin\/users\//,route=>{deletes++;return route.fulfill({json:{success:true}});});await alert.getByRole("button",{name:"Cancel"}).click();expect(deletes).toBe(0);
  await page.getByRole("button",{name:"Create user",exact:true}).click();const modal=page.getByRole("dialog",{name:"Create New User"});await expect(modal).toBeVisible();await modal.getByRole("button",{name:"Create User",exact:true}).click();const fullName=modal.getByRole("textbox",{name:"Full Name"});await expect(fullName).toHaveAttribute("aria-invalid","true");expect(await fullName.evaluate(el=>el.getAttribute("aria-describedby")?.split(" ").some(id=>document.getElementById(id)?.getAttribute("role")==="alert"))).toBe(true);
  await fullName.fill("New colleague");await modal.getByRole("textbox",{name:"Email"}).fill("new@example.test");await modal.getByLabel("Password").fill("synthetic-password");await modal.getByLabel("Organization").selectOption({label:"Planning Office"});let requests=0;await page.route("**/admin/users/create",async route=>{requests++;await new Promise(resolve=>setTimeout(resolve,600));await route.fulfill({status:400,json:{detail:"Synthetic save rejected"}});});
  await modal.getByRole("button",{name:"Create User",exact:true}).click();await expect(modal.getByRole("button",{name:/Creating/})).toBeDisabled();await page.keyboard.press("Escape");await expect(modal).toBeVisible();await expect(modal.getByRole("alert").filter({hasText:"Changes were not saved"})).toBeVisible();expect(requests).toBe(1);await expect(fullName).toHaveValue("New colleague");await expect(modal.getByRole("button",{name:"Create User",exact:true})).toBeEnabled();
  await page.mouse.move(0,0);
  await expect.poll(()=>modal.getByRole("button",{name:"Create User",exact:true}).evaluate(el=>getComputedStyle(el).backgroundColor)).toBe("rgb(12, 111, 107)");
  const rect=(await modal.boundingBox())!;expect(rect.x).toBeGreaterThanOrEqual(0);expect(rect.x+rect.width).toBeLessThanOrEqual(width);await page.screenshot({path:info.outputPath(`admin-form-${width}.png`)});await modal.getByRole("button",{name:"Cancel",exact:true}).click();const discard=page.getByRole("alertdialog",{name:"Discard unsaved changes?"});await expect(discard).toBeVisible();await discard.getByRole("button",{name:"Keep editing"}).click();await expect(fullName).toHaveValue("New colleague");await modal.getByRole("button",{name:"Cancel",exact:true}).click();await discard.getByRole("button",{name:"Discard",exact:true}).click();expect(requests).toBe(1);await expect(page.getByRole("button",{name:"Create user",exact:true})).toBeFocused();await page.screenshot({path:info.outputPath(`admin-directory-${width}.png`)});
});
