import { openProjectAction, openCompletionRequirements } from './fixtures/projectActions';
import { test, expect } from '@playwright/test';
import { projectWorkspaceFixture } from './fixtures/projectWorkspace';
const partner='10000000-0000-4000-8000-000000000002';
const partnerHead='00000000-0000-4000-8000-000000000002';
test('Lead invites an Office and hands over responsibility without assigning its staff',async({page},info)=>{
 test.setTimeout(90_000);
 const r=await projectWorkspaceFixture(page,'head');
 Object.assign(r.tasks[0],{status:'pending_assignment',assigned_to:null,team_member_ids:[]});
 r.organizations.push({id:partner,name:'City Engineering Office',head_user_id:partnerHead,is_active:true,path:'engineering_office',slug:'engineering_office',org_type:'department'});
 r.projectOffices.push({id:'lead',project_id:r.project,office_id:r.org,relationship_type:'lead',invitation_status:'joined'});
 let sent:any, handover:any;const invites:any[]=[];
 await page.route('**/rest/v1/rpc/phase6_responsible_office',async route=>{
  handover=route.request().postDataJSON();Object.assign(r.tasks[0],{org_id:handover.p_office});await route.fulfill({json:null});
 });
 await page.route('**/controlpanelEflow/api/invitations/**',async route=>{
  if(route.request().method()==='POST') {sent=route.request().postDataJSON();r.projectOffices.push({id:'partner',project_id:r.project,office_id:partner,relationship_type:sent.access,invitation_status:'pending',contact_email:sent.email});invites.push({id:'invite',project_office_id:'partner',status:'pending',email_delivery_status:'sent'});return route.fulfill({json:invites[0]});}
  return route.fulfill({json:{invitations:invites}});
 });
 await page.goto('/projects?page=Projects&project='+r.project+'&view=tasks');
 await expect(page.locator('.eflow-productivity-sidebar').first()).toBeVisible({timeout:30000});
 const sidebar=page.locator('.eflow-productivity-sidebar').first();await sidebar.hover();
 await sidebar.getByRole('button',{name:'Workspaces',exact:true}).first().press('Enter');
 await expect(page.getByRole('region',{name:'Project main table'})).toBeVisible({timeout:30000});
 await openProjectAction(page,'Project Offices');
 await expect(page.getByRole('region',{name:'Project Office collaboration'})).toBeVisible({timeout:30000});
 await page.getByRole('button',{name:'Invite Office',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'Let’s bring another Office in.'});
 await dialog.getByRole('combobox',{name:'Office',exact:true}).selectOption(partner);
 await dialog.getByLabel('Head / contact email').fill('engineering@example.test');
 const bounds=(await dialog.boundingBox())!;expect(bounds.width).toBeGreaterThan(850);expect(bounds.height).toBeGreaterThan(500);
 await page.screenshot({path:info.outputPath('invite-office-desktop.png')});
 await dialog.getByRole('button',{name:'Invite Office',exact:true}).click();
 await page.getByRole('alertdialog',{name:'Invite this Office?'}).getByRole('button',{name:'Invite Office',exact:true}).click();
 await expect(dialog.getByRole('status')).toContainText('Invitation sent');expect(sent.access).toBe('collaborating');expect(sent.account_role).toBeUndefined();
 await dialog.getByRole('button',{name:'Done',exact:true}).click();
 await expect(page.locator('.po-office-table tbody tr').filter({hasText:'City Engineering Office'})).toContainText('Invitation pending');
 await page.screenshot({path:info.outputPath('office-workspace-desktop.png')});
 Object.assign(r.projectOffices[1],{invitation_status:'joined'});invites[0].status='accepted';
 await page.goto('/projects?page=Projects&project='+r.project+'&view=tasks');
 await expect(page.getByRole('region',{name:'Project main table'})).toBeVisible({timeout:30000});
 await page.getByRole('button',{name:'Responsible Office for Prepare community assessment'}).click();
 await page.getByRole('combobox',{name:'Assign Office'}).selectOption(partner);
 await expect.poll(()=>handover?.p_task).toBe(r.tasks[0].id);expect(handover.p_office).toBe(partner);
 await expect(page.getByRole('combobox',{name:'Owner for Prepare community assessment'})).toBeDisabled();
});
test('Collaborating Head sees a roomy own-Office member picker and only edits its own tasks',async({page},info)=>{
 test.setTimeout(90_000);const r=await projectWorkspaceFixture(page,'head');
 r.projectOffices.push({id:'lead',project_id:r.project,office_id:partner,relationship_type:'lead',invitation_status:'joined'},{id:'own',project_id:r.project,office_id:r.org,relationship_type:'collaborating',invitation_status:'joined'});
 r.projects[0].org_id=partner;r.organizations.push({id:partner,name:'Lead Office',head_user_id:partnerHead,is_active:true,path:'engineering_office',slug:'engineering_office',org_type:'department'});
 for(let i=0;i<8;i++)r.profiles.push({id:'person-'+i,org_id:r.org,full_name:'Office Member '+i,email:'person'+i+'@example.test',role:'member',is_active:true});
 r.profiles.push({id:'foreign',org_id:partner,full_name:'Other Office Employee',email:'other@example.test',role:'member',is_active:true});
 r.tasks[1].org_id=partner;
 await page.goto('/projects?page=Projects&project='+r.project+'&view=tasks');
 await expect(page.locator('.eflow-productivity-sidebar').first()).toBeVisible({timeout:30000});
 const sidebar=page.locator('.eflow-productivity-sidebar').first();await sidebar.hover();
 await sidebar.getByRole('button',{name:'Workspaces',exact:true}).first().press('Enter');
 await expect(page.getByRole('region',{name:'Project main table'})).toBeVisible({timeout:30000});
 await expect(page.getByRole('combobox',{name:'Owner for Prepare community assessment'})).toBeEnabled();
 await expect(page.getByRole('combobox',{name:'Owner for Coordinate Office briefing'})).toBeDisabled();
 await openProjectAction(page,'Project Offices');
 await page.getByRole('button',{name:'Select own members',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'Planning Office’s project team'});
 await expect(dialog).toContainText('Office Member 7');await expect(dialog).not.toContainText('Other Office Employee');
 const visible=await dialog.locator('.po-member-list label').evaluateAll(rows=>rows.filter(row=>{const r=row.getBoundingClientRect(),p=row.parentElement!.getBoundingClientRect();return r.top>=p.top&&r.bottom<=p.bottom;}).length);
 expect(visible).toBeGreaterThanOrEqual(4);
 const saveBounds=(await dialog.getByRole('button',{name:'Save project team'}).boundingBox())!;
 expect(saveBounds.y+saveBounds.height).toBeLessThanOrEqual(page.viewportSize()!.height);
 await page.screenshot({path:info.outputPath('own-office-team-desktop.png')});
 await page.setViewportSize({width:390,height:844});await expect(dialog).toBeVisible({timeout:30000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:info.outputPath('own-office-team-mobile.png')});
});
test('Observer opens the project without editable owners or task planning',async({page})=>{
 test.setTimeout(90_000);const r=await projectWorkspaceFixture(page,'member');
 r.projectOffices.push({id:'lead',project_id:r.project,office_id:partner,relationship_type:'lead',invitation_status:'joined'},{id:'observer',project_id:r.project,office_id:r.org,relationship_type:'observer',invitation_status:'joined',contact_user_id:r.id});
 r.projects[0].org_id=partner;
 await page.goto('/projects?page=Projects&project='+r.project+'&view=tasks');
 await expect(page.locator('.eflow-productivity-sidebar').first()).toBeVisible({timeout:30000});
 const sidebar=page.locator('.eflow-productivity-sidebar').first();await sidebar.hover();
 await sidebar.getByRole('button',{name:'Workspaces',exact:true}).first().press('Enter');
 await expect(page.getByRole('region',{name:'Project main table'})).toBeVisible({timeout:30000});
 await expect(page.getByRole('combobox',{name:'Owner for Prepare community assessment'})).toBeDisabled();
 await expect(page.getByRole('button',{name:'New task',exact:true})).toHaveCount(0);
 await openProjectAction(page,'Project Offices');
 await expect(page.getByRole('region',{name:'Project Office collaboration'})).toContainText('Observer · read only');
 await expect(page.getByRole('button',{name:'Invite Office',exact:true})).toHaveCount(0);
});
