import { openCompletionRequirements } from './fixtures/projectActions';
import { expect, test, type Page } from '@playwright/test';
import { projectWorkspaceFixture } from './fixtures/projectWorkspace';
const source='Planning Office prepares community outreach. This implementation proposal describes objectives, activities, schedule, budget estimates, evaluation and evidence. Gather community needs and review the assessment before coordinating outreach and documenting the delivered outcomes.';
async function ai(page:Page, response:unknown) {
 await page.route('**/controlpanelEflow/api/ai/status',route=>route.fulfill({json:{ai_endpoint:'http://127.0.0.1:5190/controlpanelEflow/api',ai_endpoint_status:'online',ai_endpoint_heartbeat:new Date().toISOString()}}));
 await page.route('**/controlpanelEflow/api/proposals/validate',route=>route.fulfill({json:{is_proposal:true,score:100,message:'Valid source'}}));
 await page.route('**/controlpanelEflow/api/ai/jobs',route=>route.fulfill({status:202,json:{job_id:'phase15',status:'completed',jobs_ahead:0,result:{message:{content:JSON.stringify(response)}}}}));
}
function pdf(text:string) {
 const content=`BT /F1 10 Tf 20 770 Td (${text}) Tj ET`,objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 3000 800] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`];let body='%PDF-1.4\n';const offsets:number[]=[];objects.forEach((item,i)=>{offsets.push(Buffer.byteLength(body));body+=`${i+1} 0 obj\n${item}\nendobj\n`;});const xref=Buffer.byteLength(body);body+=`xref\n0 6\n0000000000 65535 f \n${offsets.map(n=>`${String(n).padStart(10,'0')} 00000 n \n`).join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(body);
}
test('Reviewed project sections preserve source and require one impact confirmation before creating work',async({page},info)=>{
 test.setTimeout(90_000);const r=await projectWorkspaceFixture(page,'head');let writes=0;
 await ai(page,{schemaVersion:1,project:{title:'Reviewed outreach',description:'Reviewed description',objectives:'Serve communities',startDate:'2026-10-10',targetDate:'2026-10-20'},offices:[],groups:[{key:'g',title:'Preparation',color:'#579bfc',existingGroupId:'',tasks:[{key:'t',title:'Assess needs',description:'Gather evidence',priority:'medium',estimatedHours:8,startDate:'',dueDate:'',officeKey:'',dependencies:[],sourceQuote:'',subitems:[]}]}],warnings:['Check the source schedule.']});
 await page.route('**/rest/v1/rpc/phase5_import_project_work',route=>{writes++;return route.fulfill({json:{taskCount:1,subitemCount:0,groupCount:1,taskIds:{t:'saved'},groupIds:['g']}});});
 await page.getByRole('button',{name:'New task options'}).click();await page.getByRole('menuitem',{name:'Import project document'}).click();const initial=page.getByRole('dialog',{name:'Turn a document into project work'});await initial.getByLabel('Document text or project brief').fill(source);await initial.getByRole('button',{name:'Generate draft'}).click();const dialog=page.getByRole('dialog',{name:'Review your project plan'});await expect(dialog.getByLabel('Task name t')).toBeVisible();
 const navigation=dialog.getByRole('navigation',{name:'Review sections'});await navigation.getByRole('button',{name:/Warnings/}).click();await expect(dialog.getByText('Check the source schedule.')).toBeVisible();await navigation.getByRole('button',{name:/Project details/}).click();await dialog.getByLabel('Use these reviewed details for the current project').check();await navigation.getByRole('button',{name:/Groups and work/}).click();expect(writes).toBe(0);
 await dialog.getByRole('button',{name:'Add to Project'}).click();const review=page.getByRole('alertdialog',{name:'Add reviewed work to project?'});await expect(review).toContainText('1 groups · 1 tasks · 0 subitems');await expect(review).toContainText('Replace project details');await review.getByRole('button',{name:'Cancel',exact:true}).click();expect(writes).toBe(0);
 await page.setViewportSize({width:320,height:844});await expect.poll(async()=>{const b=await dialog.boundingBox();return !!b && b.x>=-1 && b.x+b.width<=321 && b.y>=-1;}).toBe(true);await page.screenshot({path:info.outputPath('import-review-320.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await dialog.press('Escape');await page.getByRole('alertdialog',{name:'Discard unsaved changes?'}).getByRole('button',{name:'Keep editing',exact:true}).click();await expect(dialog.getByLabel('Task name t')).toHaveValue('Assess needs');await dialog.getByRole('button',{name:'Add to Project'}).click();await page.getByRole('alertdialog',{name:'Add reviewed work to project?'}).getByRole('button',{name:'Add reviewed work',exact:true}).click();await expect(page.getByRole('dialog',{name:'Work added to your project'})).toContainText('1 tasks');expect(writes).toBe(1);expect(r.tasks.length).toBe(3);
});
test('PDF work-plan review saves only its persistent draft, keeps failed autosave edits and retries saving',async({page},info)=>{
 test.setTimeout(90_000);const r=await projectWorkspaceFixture(page,'head',false,{landingOnly:true});r.projects.length=0;let creates=0,saves=0,operational=0;let saved:Record<string,unknown>={};
 await ai(page,{tasks:[{title:'Draft assessment',description:'Gather evidence',estimatedDuration:'1 day',priority:'medium',requiredSkills:[],recommendedEmployeeIds:[],budgetDecision:'missing',budgetLines:[],subtasks:['Collect evidence']}]});
 await page.route('**/storage/v1/object/**',route=>route.fulfill({json:{Key:'source.pdf'}}));
 await page.route('**/rest/v1/rpc/create_collaboration_draft',route=>{creates++;const p=route.request().postDataJSON();saved={id:'draft',title:p.p_title,owner_org_id:r.org,owner_user_id:r.id,source_type:'ai_pdf',status:'draft',working_snapshot:p.p_snapshot,created_at:new Date().toISOString()};return route.fulfill({json:[saved]});});
 await page.route('**/rest/v1/rpc/set_collaboration_source_document',route=>route.fulfill({json:null}));
 await page.route('**/rest/v1/rpc/autosave_collaboration_draft',route=>{saves++;if(saves===1)return route.fulfill({status:403,json:{code:'42501',message:'Draft update denied'}});saved={...saved,working_snapshot:route.request().postDataJSON().p_snapshot};return route.fulfill({json:[saved]});});
 page.on('request',req=>{if(/assign_task_with_details|phase3_create_task|phase5_import_project_work|phase65_import_project_work|commit_collaboration/.test(req.url()))operational++;});
 await page.goto('/projects?page=Projects');await page.getByRole('button',{name:'Create project options'}).last().click();await page.getByRole('menuitem',{name:'Import proposal',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Create a work plan'});await dialog.locator('#proposal-import-file').setInputFiles({name:'plan.pdf',mimeType:'application/pdf',buffer:pdf(source)});await expect(dialog.getByRole('button',{name:'Edit task',exact:true}).first()).toBeVisible({timeout:30_000});expect(creates).toBe(1);expect(operational).toBe(0);
 const sections=dialog.getByRole('navigation',{name:'Review sections'});await sections.getByRole('button',{name:/Timeline and budget/}).click();await expect(dialog.getByText(/not authorized or settled funds/).first()).toBeVisible();await sections.getByRole('button',{name:/Hierarchy and tasks/}).click();await dialog.getByRole('button',{name:'Edit task',exact:true}).first().click();await dialog.getByLabel('Task title').first().fill('Reviewed assessment');await expect(dialog.getByRole('alert')).toContainText('Draft update denied');await dialog.getByRole('button',{name:'Retry saving draft'}).click();await expect(dialog.getByText('Current draft saved')).toBeVisible();expect(saves).toBe(2);expect(operational).toBe(0);await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('workplan-review-mobile.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('Task inspector staffing retains selection after eligibility denial and assigns only after reviewed fresh context',async({page},info)=>{
 test.setTimeout(90_000);const r=await projectWorkspaceFixture(page,'head');Object.assign(r.tasks[0],{assigned_to:null,status:'pending_assignment'});let reads=0,assigned=0,deny=false;
 const candidates=[{id:r.id,name:'Alex Rivera',skills:['Planning'],training:[],education:[],experience:[],specializations:[],certifications:[],experience_summary:'',activeTasks:2,remainingHours:6,unknownEffortTasks:1}];
 await page.route('**/controlpanelEflow/api/staffing/**/context',route=>{reads++;return deny?route.fulfill({status:403,json:{detail:'Office authority changed'}}):route.fulfill({json:{task:{id:r.tasks[0].id,title:r.tasks[0].title,skills:['Planning']},candidates,excludedUnconfirmed:2}});});await ai(page,{recommendations:[{userId:r.id,evidence:['Planning']}]});await page.route('**/rest/v1/rpc/assign_task_with_details',route=>{assigned++;Object.assign(r.tasks[0],{assigned_to:r.id,status:'todo'});return route.fulfill({json:[r.tasks[0]]});});
 await page.goto('/projects?page=Projects&project='+r.project+'&view=tasks');await page.getByRole('button',{name:'Open Prepare community assessment',exact:true}).click();const inspector=page.getByRole('dialog',{name:'Task details: Prepare community assessment'});await inspector.getByRole('button',{name:'Details',exact:true}).click();await inspector.getByRole('button',{name:'Recommend staff',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Recommend staff',exact:true});await dialog.getByRole('button',{name:'Generate recommendations'}).click();await dialog.getByRole('radio').check();expect(assigned).toBe(0);deny=true;await dialog.getByRole('button',{name:'Confirm owner'}).click();await page.getByRole('alertdialog',{name:'Assign recommended owner?'}).getByRole('button',{name:'Assign owner',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Office authority changed');await expect(dialog.getByRole('radio')).toBeChecked();expect(assigned).toBe(0);deny=false;await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('staffing-denial-mobile.png')});await dialog.getByRole('button',{name:'Confirm owner'}).click();await page.getByRole('alertdialog',{name:'Assign recommended owner?'}).getByRole('button',{name:'Assign owner',exact:true}).click();await expect(dialog).not.toBeVisible();expect(assigned).toBe(1);expect(reads).toBe(4);
});
test('Owner PDS review retries extraction, retains failed profile edits and confirms the saved summary separately',async({page},info)=>{
 test.setTimeout(90_000);const r=await projectWorkspaceFixture(page,'member',false,{landingOnly:true});const values={skills:['Planning'],education:[],trainings:[],certifications:[],work_experience:[],specializations:[],competency_summary:'Work summary'};let profile={...values,user_id:r.id,confirmed_by_user:false},status='failed',updates=0,confirms=0,retries=0,uploaded=false;
 await page.route(/\/controlpanelEflow\/api\/professional-profile\//,route=>{const req=route.request();if(req.url().endsWith('/confirm')){confirms++;profile={...profile,confirmed_by_user:true};}else if(req.method()==='PATCH'){updates++;if(updates===1)return route.fulfill({status:403,json:{detail:'Profile save denied'}});profile={...profile,...req.postDataJSON(),confirmed_by_user:false};}return route.fulfill({json:{profile}});});
 await page.route(/\/controlpanelEflow\/api\/pds\//,route=>{const path=new URL(route.request().url()).pathname;if(path.endsWith('/upload')){uploaded=true;return route.fulfill({json:{id:'pdf',original_filename:'PDS.pdf',processing_status:'failed'}});}if(path.endsWith('/process')){retries++;status='completed';return route.fulfill({json:{processing_status:'pending'}});}if(path.endsWith('/professional-draft'))return route.fulfill({json:{draft:{...values,skills:['Extracted planning']}}});return route.fulfill({json:{documents:uploaded?[{id:'pdf',original_filename:'PDS.pdf',processing_status:status,processing_error:status==='failed'?'Extraction failed':''}]:[]}});});
 await page.getByRole('button',{name:'Help and Getting Started',exact:true}).click();await page.getByRole('button',{name:'Review your professional profile',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Your professional profile'});await dialog.getByLabel('Upload your PDS PDF').setInputFiles({name:'PDS.pdf',mimeType:'application/pdf',buffer:pdf(source)});await dialog.getByRole('button',{name:'Retry processing'}).click();await dialog.getByRole('button',{name:'Review extracted draft'}).click();await expect(dialog.getByLabel('Skills')).toHaveValue('Extracted planning');await dialog.press('Escape');await page.getByRole('alertdialog',{name:'Discard unsaved changes?'}).getByRole('button',{name:'Keep editing',exact:true}).click();await expect(dialog.getByLabel('Skills')).toHaveValue('Extracted planning');expect(updates).toBe(0);expect(confirms).toBe(0);await dialog.getByRole('button',{name:'Save changes'}).click();await expect(dialog.getByRole('alert')).toContainText('Profile save denied');await expect(dialog.getByLabel('Skills')).toHaveValue('Extracted planning');await page.setViewportSize({width:320,height:844});await expect.poll(async()=>{const b=await dialog.boundingBox();return !!b && b.x>=-1 && b.x+b.width<=321 && b.y>=-1;}).toBe(true);await expect.poll(()=>dialog.locator('.eflow-professional-panel').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.screenshot({path:info.outputPath('profile-draft-320.png')});await dialog.getByRole('button',{name:'Save changes'}).click();await dialog.getByRole('button',{name:'Confirm profile'}).click();await page.getByRole('alertdialog',{name:'Confirm professional summary?'}).getByRole('button',{name:'Confirm summary',exact:true}).click();await expect(dialog.getByText('Confirmed',{exact:true})).toBeVisible();expect(updates).toBe(2);expect(confirms).toBe(1);expect(retries).toBe(1);
});
const closeout={tasks:3,completed:1,cancelled:0,budgetEstimate:100,offices:1,evidence:1,contributors:1,startDate:'2026-10-01',targetDate:'2026-10-20',financial:{requested:100,approved:100,settled:0,open:1}};
test('Official readiness blockers link to Office and task views, and material changes refresh current checks',async({page},info)=>{
 const r=await projectWorkspaceFixture(page,'head');let accepted=false;
 await page.route('**/rest/v1/rpc/phase7_*',route=>{const name=new URL(route.request().url()).pathname.split('/').at(-1);return route.fulfill({json:name==='phase7_closeout_summary'?closeout:{projectId:r.project,governed:false,ready:false,canActivate:false,stage:'Planning',checks:[{key:'invitations',label:'Office invitations accepted',ok:accepted,detail:accepted?'All joined':'1 Office awaiting acceptance'},{key:'staffing',label:'Required owners',ok:false,detail:'1 task needs an owner'}]}});});await page.route('**/rest/v1/rpc/get_project_completion_readiness',route=>route.fulfill({json:{projectId:r.project,status:'planning',canComplete:false,blockers:[{kind:'cash',id:'cash',title:'Unsettled request',status:'released',detail:'Accounting must settle this request.'}]}}));
 await openCompletionRequirements(page);let panel=page.getByRole('region',{name:'Project readiness reviews'});await expect(panel).toContainText('1 Office awaiting acceptance');await panel.getByRole('button',{name:'Resolve in Project Offices'}).click();await expect(page.getByRole('region',{name:'Project Office collaboration'})).toBeVisible();accepted=true;await openCompletionRequirements(page);panel=page.getByRole('region',{name:'Project readiness reviews'});await expect(panel).toContainText('All joined');await expect(panel.getByRole('button',{name:'Activate project',exact:true})).toBeDisabled();await expect(page.getByRole('dialog',{name:'Mark project complete'}).getByRole('button',{name:'Review financial settlement'})).toBeVisible();await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('readiness-resolution-mobile.png')});await panel.getByRole('button',{name:'Review in Main table'}).click();await expect(page.getByRole('region',{name:'Project main table'})).toBeVisible();
});
test('Missing readiness deployment explains administrator recovery and governed projects retain Proposal Context handoff',async({page})=>{
 const r=await projectWorkspaceFixture(page,'head');let installed=false;
 await page.route('**/rest/v1/rpc/get_project_completion_readiness',route=>route.fulfill({json:{projectId:r.project,canComplete:false,blockers:[]}}));
 await page.route('**/rest/v1/rpc/phase7_*',route=>{if(!installed)return route.fulfill({status:404,json:{code:'PGRST202',message:'RPC unavailable'}});return route.fulfill({json:new URL(route.request().url()).pathname.endsWith('/phase7_closeout_summary')?closeout:{projectId:r.project,governed:true,ready:false,canActivate:false,stage:'Governed',checks:[{key:'structure',label:'Governance review',ok:false,detail:'Use the existing proposal review'}]}});});
 await openCompletionRequirements(page);const panel=page.getByRole('region',{name:'Project readiness reviews'});await expect(panel.getByRole('alert')).toContainText('Contact your administrator');await expect(panel.getByRole('button',{name:'Refresh plan reviews'})).toBeEnabled();installed=true;Object.assign(r.projects[0],{source_collaboration_draft_id:'governed'});await page.goto('/projects?page=Projects&project='+r.project+'&view=readiness');await openCompletionRequirements(page);await expect(panel).toContainText('Governed');await expect(panel.getByRole('button',{name:'Activate project'})).toHaveCount(0);await panel.getByRole('button',{name:'Open proposal review'}).first().click();await expect(page).toHaveURL(/view=proposal_context/);
});
