import { test, expect } from '@playwright/test';
import { projectWorkspaceFixture as fixture } from './fixtures/projectWorkspace';
const title='Prepare community assessment';
test.beforeEach(async({page})=>{test.setTimeout(90_000);await page.setViewportSize({width:1440,height:1000});});

test('column widths, alignment, visibility and sticky task context persist locally',async({page},info)=>{
 test.setTimeout(90_000);const records=await fixture(page,'head');let writes=0;page.on('request',request=>{if(/phase3_(patch_task|create_task|reorder_tasks)/.test(request.url())&&request.method()==='POST')writes++;});
 const table=page.getByRole('table',{name:'To do tasks',exact:true});const resize=table.getByRole('separator',{name:'Resize Task column'});await resize.focus();await resize.press('Shift+ArrowRight');await expect(resize).toHaveAttribute('aria-valuenow','352');
 const handle=await table.getByRole('separator',{name:'Resize Owner column'}).boundingBox();await page.mouse.move(handle!.x+handle!.width/2,handle!.y+handle!.height/2);await page.mouse.down();await page.mouse.move(handle!.x+handle!.width/2+40,handle!.y+handle!.height/2);await page.mouse.up();await expect(table.getByRole('separator',{name:'Resize Owner column'})).toHaveAttribute('aria-valuenow','220');
 const widths=await table.evaluate(element=>{const row=element.querySelector('tbody tr')!;return [element.querySelector('thead tr')!.children[1].getBoundingClientRect().width,row.children[1].getBoundingClientRect().width,element.querySelector('tfoot tr')!.children[1].getBoundingClientRect().width];});expect(widths.every(width=>Math.abs(width-352)<2)).toBe(true);
 const scroll=page.locator('.pt-table-scroll').first();await scroll.evaluate(element=>element.scrollLeft=650);const row=table.locator('.pt-task-row').first();const actions=await row.locator('td').first().boundingBox(),name=await row.locator('.pt-task-name').boundingBox(),bounds=await scroll.boundingBox();expect(Math.abs(actions!.x-bounds!.x-5)).toBeLessThan(3);expect(Math.abs(name!.x-actions!.x-actions!.width)).toBeLessThan(3);
 await row.getByRole('button',{name:'Actions for '+title,exact:true}).click();await expect(page.getByRole('menuitem',{name:'Task team & contributors',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('menu')).toHaveCount(0);await page.screenshot({path:info.outputPath('sticky-columns-desktop.png')});
 await scroll.evaluate(element=>element.scrollLeft=0);await page.getByRole('button',{name:'Column actions for Budget estimate'}).click();await page.getByRole('menuitem',{name:'Hide column',exact:true}).click();await page.reload();await expect(table.getByRole('separator',{name:'Resize Task column'})).toHaveAttribute('aria-valuenow','352');await expect(table.getByRole('columnheader',{name:'Budget estimate',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Columns',exact:true}).click();await page.getByRole('button',{name:'Reset column widths',exact:true}).click();await page.keyboard.press('Escape');await expect(table.getByRole('separator',{name:'Resize Task column'})).toHaveAttribute('aria-valuenow','320');await expect(table.getByRole('columnheader',{name:'Budget estimate',exact:true})).toHaveCount(0);expect(writes).toBe(0);expect(records.tasks.map(task=>task.workspace_position)).toEqual([0,1,2]);await expect(page.locator('[data-slot=popover-content]')).toHaveCount(0);
 await page.screenshot({path:info.outputPath('table-layout-desktop.png'),fullPage:true});
});

test('date and dependency drafts guard close and retain denied edits for scoped retry',async({page},info)=>{
 test.setTimeout(90_000);const records=await fixture(page,'head',true);records.tasks[0].deadline='2026-10-09T17:45:00+08:00';await page.reload();
 const patches:Record<string,unknown>[]=[];let deny=true;await page.route('**/rest/v1/rpc/phase3_patch_task',route=>{patches.push(route.request().postDataJSON().p_patch);return deny?route.fulfill({status:403,json:{message:'Synthetic planning denial'}}):route.fallback();});
 await page.getByRole('button',{name:'Edit dates for '+title,exact:true}).click();const editor=page.locator('.pt-planning-editor').filter({hasText:'Task timeline'});await editor.getByLabel('Due date',{exact:true}).fill('2026-10-14');await page.getByRole('tab',{name:'Board',exact:true}).click();await page.getByRole('button',{name:'Keep editing',exact:true}).click();await expect(page.getByRole('tab',{name:'Main table',exact:true})).toHaveAttribute('aria-selected','true');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Keep editing',exact:true}).click();await expect(editor.getByLabel('Due date',{exact:true})).toHaveValue('2026-10-14');
 await editor.getByRole('button',{name:'Save dates',exact:true}).click();await expect(editor.getByRole('alert')).toContainText('Synthetic planning denial');await expect(editor.getByLabel('Due date',{exact:true})).toHaveValue('2026-10-14');await page.screenshot({path:info.outputPath('timeline-error-desktop.png')});deny=false;await editor.getByRole('button',{name:'Save dates',exact:true}).click();await expect(editor.getByRole('status')).toContainText('Dates saved');expect(patches).toEqual([{start_date:'2026-10-03',deadline:'2026-10-14T17:45:00+08:00'},{start_date:'2026-10-03',deadline:'2026-10-14T17:45:00+08:00'}]);await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Edit dependencies for '+title,exact:true}).click();const deps=page.locator('.pt-planning-editor');await deps.getByRole('checkbox',{name:'Coordinate Office briefing',exact:true}).check();await deps.getByRole('button',{name:'Save dependencies',exact:true}).click();await expect(deps.getByRole('alert')).toContainText('cycle');expect(patches).toHaveLength(2);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Discard',exact:true}).click();await expect(deps).toHaveCount(0);
 const effort=page.getByRole('spinbutton',{name:'Effort hours for '+title,exact:true});deny=true;await effort.fill('16');await effort.press('Enter');const cell=effort.locator('..');await expect(cell.getByRole('alert')).toContainText('Synthetic planning denial');await expect(effort).toHaveValue('16');deny=false;await cell.getByRole('button',{name:'Retry',exact:true}).click();await expect(cell.getByRole('status')).toContainText('Saved');expect(patches.slice(2)).toEqual([{estimated_hours:16},{estimated_hours:16}]);
});

test('filter chips clear one or all without changing canonical manual ordering',async({page},info)=>{
 const records=await fixture(page,'head');let reorder=0;page.on('request',request=>{if(request.url().includes('phase3_reorder_tasks'))reorder++;});
 await page.getByRole('textbox',{name:'Search project tasks'}).fill('Prepare');await page.getByRole('combobox',{name:'Filter owner',exact:true}).selectOption(records.id);await page.getByRole('combobox',{name:'Sort tasks',exact:true}).selectOption('title');await expect(page.locator('.pt-task-row')).toHaveCount(1);
 await page.getByRole('button',{name:'Remove Search: Prepare',exact:true}).click();await expect(page.locator('.pt-task-row')).toHaveCount(3);await expect(page.getByRole('combobox',{name:'Filter owner',exact:true})).toHaveValue(records.id);await expect(page.getByText(/appointed task lead/)).toBeVisible();await expect(page.getByRole('columnheader',{name:'Task',exact:true})).toHaveAttribute('aria-sort','ascending');await page.screenshot({path:info.outputPath('filters-desktop.png')});
 await page.getByRole('button',{name:'Clear filters',exact:true}).click();await expect(page.getByRole('combobox',{name:'Sort tasks',exact:true})).toHaveValue('title');await page.getByRole('button',{name:'Restore manual order',exact:true}).click();expect(records.tasks.map(task=>task.workspace_position)).toEqual([0,1,2]);expect(reorder).toBe(0);
 await page.getByRole('textbox',{name:'Search project tasks'}).fill('Missing task');await expect(page.getByText('No tasks match these filters. Clear filters to see all project work.')).toBeVisible();await page.getByRole('button',{name:'Remove Search: Missing task',exact:true}).click();await expect(page.locator('.pt-task-row')).toHaveCount(3);
});

test('group creation guards its draft and empty deletion confirms impact and retries denial',async({page},info)=>{
 test.setTimeout(90_000);const records=await fixture(page,'head');await page.getByRole('button',{name:'Group actions for To do',exact:true}).click();await expect(page.getByRole('menuitem',{name:'Delete empty group',exact:true})).toBeDisabled();await expect(page.getByText('The default group must remain available for project work.')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('menu')).toHaveCount(0);
 await page.getByRole('button',{name:'New group',exact:true}).click();const create=page.getByRole('dialog',{name:'New group',exact:true});await expect(create).toBeVisible({timeout:5000});await create.getByRole('textbox',{name:'Group name',exact:true}).fill('Follow-up');await create.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Keep editing',exact:true}).click();await expect(create.getByRole('textbox',{name:'Group name',exact:true})).toHaveValue('Follow-up');await page.screenshot({path:info.outputPath('new-group-draft-desktop.png')});await create.getByRole('button',{name:'Add group',exact:true}).click();await expect(create).toHaveCount(0);await expect(page.getByRole('button',{name:'Group actions for Follow-up',exact:true})).toBeVisible();
 let attempts=0;await page.route('**/rest/v1/project_groups?**',route=>{if(route.request().method()!=='DELETE')return route.fallback();attempts++;if(attempts===1)return route.fulfill({status:403,json:{message:'Synthetic group denial'}});const id=new URL(route.request().url()).searchParams.get('id')!.slice(3);const index=records.groups.findIndex(group=>group.id===id);records.groups.splice(index,1);return route.fulfill({json:[{id}]});});
 await page.getByRole('button',{name:'Group actions for Follow-up',exact:true}).click();await page.getByRole('menuitem',{name:'Delete empty group',exact:true}).click();const confirm=page.getByRole('alertdialog',{name:'Delete Follow-up?',exact:true});await expect(confirm).toContainText('No tasks or task history will be deleted');await confirm.getByRole('button',{name:'Cancel',exact:true}).click();expect(attempts).toBe(0);
 await page.getByRole('button',{name:'Group actions for Follow-up',exact:true}).click();await page.getByRole('menuitem',{name:'Delete empty group',exact:true}).click();await confirm.getByRole('button',{name:'Delete group',exact:true}).click();const error=page.getByRole('alert').filter({hasText:'Synthetic group denial'});await expect(error).toBeVisible();await page.screenshot({path:info.outputPath('group-deletion-error-desktop.png')});await error.getByRole('button',{name:'Retry deletion',exact:true}).click();await confirm.getByRole('button',{name:'Delete group',exact:true}).click();await expect(page.getByRole('button',{name:'Group actions for Follow-up',exact:true})).toHaveCount(0);expect(attempts).toBe(2);
});

test('task team entry reuses existing details and mobile sticky context leaves room for work',async({page},info)=>{
 test.setTimeout(90_000);await fixture(page,'member');await page.getByRole('button',{name:'Actions for '+title,exact:true}).click();await page.getByRole('menuitem',{name:'Task team & contributors',exact:true}).click();await expect(page.getByRole('button',{name:'Manage',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Close task detail',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Close task detail',exact:true})).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});const scroll=page.locator('.pt-table-scroll').first();await scroll.evaluate(element=>element.scrollLeft=600);const row=page.locator('.pt-task-row').first(),bounds=await scroll.boundingBox(),name=await row.locator('.pt-task-name').boundingBox();expect(name!.width).toBeLessThanOrEqual(220);expect(name!.x+name!.width).toBeLessThan(bounds!.x+bounds!.width-50);await row.getByRole('button',{name:'Actions for '+title,exact:true}).click();await expect(page.getByRole('menuitem',{name:'Add subitem',exact:true})).toBeVisible();await page.getByRole('menuitem',{name:'Add subitem',exact:true}).click();const input=page.getByRole('textbox',{name:'Add subitem to '+title,exact:true});await expect(input).toBeFocused();const box=await input.boundingBox();expect(box!.x+box!.width).toBeLessThanOrEqual(390);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:info.outputPath('sticky-subitems-mobile.png'),fullPage:true});
});

test('shared Task Lead team action explains the unresolved authority gate',async({page})=>{
 const records=await fixture(page,'member',false,{shared:true});records.projectOffices[0].relationship_type='collaborator';records.officeMembers.push({id:'membership',project_office_id:records.projectOffices[0].id,user_id:records.id,is_active:true});await page.reload();await page.getByRole('button',{name:'Actions for '+title,exact:true}).click();const team=page.getByRole('menuitem',{name:'Task team & contributors',exact:true});await expect(team).toBeDisabled();await expect(team).toContainText('responsible Office Head');await expect(page.getByRole('menuitem',{name:'Task details, evidence & review',exact:true})).toBeEnabled();
});

test('Observer inspection and closed-project table retain read-only controls',async({page})=>{
 const records=await fixture(page,'member',false,{shared:true});await expect(page.getByRole('combobox',{name:'Owner for '+title,exact:true})).toBeDisabled();await page.getByRole('button',{name:'Actions for '+title,exact:true}).click();await page.getByRole('menuitem',{name:'Task team & contributors',exact:true}).click();await expect(page.getByRole('button',{name:'Close task detail',exact:true})).toBeFocused();await expect(page.getByRole('button',{name:'Manage',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Close task detail',exact:true})).toHaveCount(0);records.projects[0].status='completed';await page.reload();await expect(page.getByRole('button',{name:'Edit task '+title,exact:true})).toBeDisabled();await expect(page.getByRole('spinbutton',{name:'Effort hours for '+title,exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'New task',exact:true})).toHaveCount(0);
});

test('Head owner appointment confirms impact and retains denied assignment for retry',async({page},info)=>{
 const records=await fixture(page,'head');const candidate='00000000-0000-4000-8000-000000000022';records.profiles.push({...records.profile,id:candidate,role:'member',full_name:'Eligible colleague'});await page.reload();const owner=page.getByRole('combobox',{name:'Owner for '+title,exact:true});let attempts=0;const payloads:Record<string,unknown>[]=[];await page.route('**/rest/v1/rpc/assign_task_with_details',route=>{attempts++;const payload=route.request().postDataJSON();payloads.push(payload);if(attempts===1)return route.fulfill({status:403,json:{message:'Synthetic appointment denial'}});Object.assign(records.tasks[0],{assigned_to:payload.p_assignee,team_member_ids:payload.p_team_member_ids});return route.fulfill({json:null});});
 await owner.selectOption(candidate);const confirm=page.getByRole('alertdialog',{name:'Change task lead',exact:true});await expect(confirm).toContainText('Existing contributors are retained');await confirm.getByRole('button',{name:'Cancel',exact:true}).click();await expect(owner).toHaveValue(records.id);expect(attempts).toBe(0);
 await owner.selectOption(candidate);await confirm.getByRole('button',{name:'Confirm task lead',exact:true}).click();const cell=owner.locator('..');await expect(cell.getByRole('alert')).toContainText('Synthetic appointment denial');await expect(owner).toHaveValue(candidate);await page.screenshot({path:info.outputPath('owner-error-desktop.png')});await cell.getByRole('button',{name:'Retry',exact:true}).click();await confirm.getByRole('button',{name:'Confirm task lead',exact:true}).click();await expect(cell.getByRole('status')).toContainText('Saved');expect(attempts).toBe(2);expect(payloads[1].p_team_member_ids).toEqual([records.id,candidate]);
});

test('mobile planning picker and explicit creation keep fields inside the viewport',async({page},info)=>{
 await fixture(page,'head',true);await page.setViewportSize({width:390,height:844});const scroll=page.locator('.pt-table-scroll').first();const dates=page.getByRole('button',{name:'Edit dates for '+title,exact:true});await scroll.evaluate(element=>element.scrollLeft=element.scrollWidth);await dates.scrollIntoViewIfNeeded();const bounds=await dates.boundingBox(),viewport=await scroll.boundingBox();await page.mouse.click(Math.min(bounds!.x+bounds!.width,viewport!.x+viewport!.width)-16,bounds!.y+bounds!.height/2);const editor=page.locator('.pt-planning-editor');await expect(editor).toBeVisible();const box=await editor.boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(390);await editor.getByLabel('Due date',{exact:true}).fill('2026-10-14');await page.screenshot({path:info.outputPath('timeline-draft-mobile.png'),animations:'disabled'});await page.keyboard.press('Escape');await page.getByRole('button',{name:'Discard',exact:true}).click();await expect(editor).toHaveCount(0);
 await page.getByRole('button',{name:'New task',exact:true}).click();const create=page.getByRole('dialog',{name:'New task',exact:true});await create.getByRole('textbox',{name:'Task name',exact:true}).fill('Retained mobile task');await page.screenshot({path:info.outputPath('new-task-draft-mobile.png'),animations:'disabled'});const input=await create.getByRole('textbox',{name:'Task name',exact:true}).boundingBox();expect(input!.x+input!.width).toBeLessThanOrEqual(390);await create.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Discard',exact:true}).click();await expect(create).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});
