import { expect, test, type Page } from '@playwright/test';
import { projectWorkspaceFixture } from './fixtures/projectWorkspace';
const member = '00000000-0000-4000-8000-000000000010';
async function peopleFixture(page: Page) {
 const r = await projectWorkspaceFixture(page, 'head', false, { landingOnly: true });
 r.profiles.push({ id: member, org_id: r.org, full_name: 'Maria Santos', email: 'maria@example.test', role: 'member', is_active: true });
 return r;
}
test('Office Team lazy professional summary, keyboard focus return and narrow labeled rows', async ({page}, info) => {
 test.setTimeout(90_000); await page.setViewportSize({ width: 1440, height: 950 }); const r = await peopleFixture(page);
 let summaries = 0, privateReads = 0;
 await page.route(/\/controlpanelEflow\/api\/professional-profile\//, route => { summaries++; return route.fulfill({ json: { profile: { user_id: member, confirmed_by_user: true, skills: ['Planning'], education: [], trainings: [], certifications: [], work_experience: [], specializations: [], competency_summary: 'Community facilitation' } } }); });
 page.on('request', req => { if (/\/pds\//.test(req.url())) privateReads++; });
 await page.goto('/team-supervision?page=Office%20Team'); const team = page.getByRole('region', { name: 'Office Team', exact: true }); await expect(team).toBeVisible({timeout:30_000});
 await expect(team.getByRole('button', { name: /Maria Santos/ })).toBeVisible(); expect(summaries).toBe(0);
 await page.screenshot({path:info.outputPath('office-team-desktop.png')});
 const source = team.locator(`[data-member-id="${member}"]`); await source.press('Enter'); const inspector = page.getByRole('dialog', {name:'Maria Santos — Office member'});
 await expect(inspector).toContainText('Not loaded'); expect(summaries).toBe(0); await inspector.getByRole('tab', {name:'Professional Profile',exact:true}).click(); await expect(inspector).toContainText('Community facilitation'); expect(privateReads).toBe(0);
 await page.screenshot({path:info.outputPath('professional-summary-desktop.png')}); await inspector.press('Escape'); await expect(inspector).not.toBeVisible(); await expect(source).toBeFocused();
 for (const width of [390,320]) { await page.setViewportSize({width,height:844}); await expect(team).toBeVisible(); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true); await source.click(); await expect(inspector).toBeVisible(); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true); await page.screenshot({path:info.outputPath(`member-inspector-${width}.png`)}); await inspector.press('Escape'); await expect(inspector).not.toBeVisible(); }
 expect(summaries).toBe(1); expect(privateReads).toBe(0);
});
test('Partial invitations retain failed rows and delivery failure does not cause duplicate creation', async ({page}, info) => {
 test.setTimeout(90_000); await peopleFixture(page); const sent: unknown[] = []; let attempts = 0;
 const invites: any[] = [];
 await page.route(/\/invitations$/, async route => {
  if (route.request().method()==='GET') return route.fulfill({json:{invitations:invites}});
  const rows = route.request().postDataJSON().invitations; sent.push(rows); attempts++;
  const results = rows.map((row:any,index:number) => { if(attempts===1 && index===1) return {email:row.email,error:'Recipient unavailable; retry this row'}; const invitation={id:'invite-'+attempts,email:row.email,account_role:row.account_role,status:'pending',created_at:new Date().toISOString(),expires_at:'2030-01-01',email_delivery_status:'failed',send_count:1,delivery_error:'Mail unavailable'}; invites.push(invitation); return {email:row.email,invitation}; });
  await route.fulfill({json:{results}});
 });
 await page.goto('/team-supervision?page=Office%20Team'); const team=page.getByRole('region',{name:'Office Team',exact:true}); await expect(team).toBeVisible({timeout:30_000}); await team.getByRole('button',{name:'Invite Member',exact:true}).click(); const dialog=page.getByRole('dialog',{name:/^Now, let/});
 await dialog.getByLabel('Email address 1').fill('created@example.test'); await dialog.getByLabel('Email address 2').fill('retry@example.test'); await dialog.getByLabel('Role 2').selectOption('accounting_staff');
 await dialog.press('Escape'); const discard=page.getByRole('alertdialog',{name:'Discard unsaved changes?'}); await expect(discard).toBeVisible(); await discard.getByRole('button',{name:'Keep editing'}).click(); await expect(dialog.getByLabel('Email address 1')).toHaveValue('created@example.test');
 await dialog.getByRole('button',{name:'Send invitations',exact:true}).click(); const review=page.getByRole('alertdialog',{name:'Send Office invitations?'}); await expect(review).toContainText('Accounting Staff'); await review.getByRole('button',{name:'Send invitations',exact:true}).click();
 await expect(dialog.getByRole('status')).toContainText('1 invitation created'); await expect(dialog.getByPlaceholder('Add email here')).toHaveCount(1); await expect(dialog.getByLabel('Email address 1')).toHaveValue('retry@example.test');
 await dialog.getByRole('button',{name:'Send invitations',exact:true}).click(); await review.getByRole('button',{name:'Send invitations',exact:true}).click(); await expect(dialog.getByRole('status')).toContainText('1 invitation created'); await expect(dialog.getByPlaceholder('Add email here')).toHaveCount(0);
 expect(sent).toEqual([[{email:'created@example.test',account_role:'member'},{email:'retry@example.test',account_role:'accounting_staff'}],[{email:'retry@example.test',account_role:'accounting_staff'}]]);
 await dialog.getByRole('button',{name:'Remind me later'}).click(); await expect(dialog).not.toBeVisible(); await expect(team.getByRole('tab',{name:'Invitations (2)',exact:true})).toHaveAttribute('data-state','active');
 await expect(team.getByRole('table')).toContainText('Pending'); await expect(team.getByRole('table')).toContainText('Failed'); await page.setViewportSize({width:390,height:844}); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true); await page.screenshot({path:info.outputPath('invitation-validity-delivery-mobile.png')});
});
test('Office Team failure has retry and filter empty can clear without hiding invitations', async ({page}) => {
 test.setTimeout(90_000); const r=await peopleFixture(page); let denied=true;
 await page.route(/\/office-team$/, route => route.fulfill(denied?{status:403,json:{detail:'Office members unavailable'}}:{json:{office_name:'Planning Office',members:r.profiles}}));
 await page.goto('/team-supervision?page=Office%20Team'); const team=page.getByRole('region',{name:'Office Team',exact:true}); await expect(team.getByRole('alert')).toContainText('Office members unavailable',{timeout:30_000});
 await team.getByRole('tab',{name:'Invitations (0)',exact:true}).click(); await expect(team).toContainText('No invitations yet'); await team.getByRole('tab',{name:'Active Members (0)',exact:true}).click(); denied=false; await team.getByRole('button',{name:'Retry',exact:true}).click(); await expect(team.getByRole('button',{name:/Maria Santos/})).toBeVisible();
 await team.getByRole('textbox',{name:'Search Office Team'}).fill('unmatched'); await expect(team).toContainText('No matching results'); await team.getByRole('button',{name:'Clear filters'}).click(); await expect(team.getByRole('button',{name:/Maria Santos/})).toBeVisible();
});
async function staffingReads(page:Page, r:Awaited<ReturnType<typeof projectWorkspaceFixture>>, actorRole:()=>string=()=> 'head') {
 await page.route('**/rest/v1/profiles?**', route=>{ const url=new URL(route.request().url()); if(url.searchParams.get('select')!=='role,is_active,org_id')return route.fallback(); return route.fulfill({json:[{role:actorRole(),is_active:true,org_id:r.org}]}); });
 await page.route('**/rest/v1/organizations?**', route=>{ const url=new URL(route.request().url()); if(url.searchParams.get('select')!=='head_user_id')return route.fallback(); return route.fulfill({json:[{head_user_id:r.id}]}); });
}
async function openOffices(page:Page, project:string) {
 await page.goto('/projects?page=Projects&project='+project+'&view=offices'); await expect(page.getByRole('region',{name:'Project Office collaboration'})).toBeVisible({timeout:30_000});
}
const partner='10000000-0000-4000-8000-000000000002';
test('Collaborating Head retains project selection on failure, guards dismissal and rechecks authority before retry',async({page},info)=>{
 test.setTimeout(90_000); const r=await peopleFixture(page); r.projects[0].org_id=partner; r.organizations.push({id:partner,name:'Lead Office',head_user_id:'foreign-head',is_active:true}); r.projectOffices.push({id:'own',project_id:r.project,office_id:r.org,relationship_type:'collaborating',invitation_status:'joined'},{id:'lead',project_id:r.project,office_id:partner,relationship_type:'lead',invitation_status:'joined'});
 let actor='head', denied=true, writes=0; await staffingReads(page,r,()=>actor);
 await page.route('**/rest/v1/rpc/phase6_set_members',async route=>{writes++;if(denied)return route.fulfill({status:403,json:{message:'Membership save denied'}});const body=route.request().postDataJSON();expect(Object.keys(body).sort()).toEqual(['p_id','p_users']);r.officeMembers.splice(0,r.officeMembers.length,...body.p_users.map((id:string)=>({project_office_id:body.p_id,user_id:id})));return route.fulfill({json:null});});
 await openOffices(page,r.project);const region=page.getByRole('region',{name:'Project Office collaboration'});await expect(region.getByRole('table')).toContainText('Lead Office');await region.getByRole('button',{name:'Select own members'}).click();const inspector=page.getByRole('dialog',{name:'Planning Office’s project team'});const person=inspector.getByRole('checkbox',{name:/Maria Santos/});await person.check();await expect(inspector).toContainText('Added: Maria Santos');
 await inspector.press('Escape');const discard=page.getByRole('alertdialog',{name:'Discard unsaved changes?'});await expect(discard).toBeVisible();await discard.getByRole('button',{name:'Keep editing'}).click();await expect(person).toBeChecked();
 await inspector.getByRole('button',{name:'Save project team',exact:true}).click();const review=page.getByRole('alertdialog',{name:'Save project team?'});await expect(review).toContainText('Maria Santos');await review.getByRole('button',{name:'Save project team',exact:true}).click();await expect(inspector.getByRole('alert')).toContainText('Membership save denied');await expect(person).toBeChecked();expect(writes).toBe(1);
 actor='member';await inspector.getByRole('button',{name:'Save project team',exact:true}).click();await expect(inspector.getByRole('alert')).toContainText('current appointed Head');expect(writes).toBe(1);await expect(person).toBeChecked();
 actor='head';denied=false;await inspector.getByRole('button',{name:'Save project team',exact:true}).click();await review.getByRole('button',{name:'Save project team',exact:true}).click();await expect(inspector).not.toBeVisible();expect(writes).toBe(2);await expect(region.locator('tbody tr').filter({hasText:'Planning Office'})).toContainText('1 selected project members');
 await page.screenshot({path:info.outputPath('project-offices-table-desktop.png')});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await region.locator('tbody tr').first().scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('project-offices-table-mobile.png')});
});
test('Project team removal previews active work and opens the shared task inspector only after discard',async({page},info)=>{
 test.setTimeout(90_000);const r=await peopleFixture(page);r.projectOffices.push({id:'own',project_id:r.project,office_id:r.org,relationship_type:'lead',invitation_status:'joined'});r.officeMembers.push({project_office_id:'own',user_id:member});r.tasks[0].assigned_to=member;r.tasks[0].team_member_ids=[member];
 await openOffices(page,r.project);await page.getByRole('button',{name:'Select own members',exact:true}).click();const inspector=page.getByRole('dialog',{name:'Planning Office’s project team'});await inspector.getByRole('checkbox',{name:/Maria Santos/}).uncheck();await expect(inspector.getByRole('alert')).toContainText('Reassign active work');await expect(inspector.getByRole('button',{name:'Save project team',exact:true})).toBeDisabled();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:info.outputPath('membership-impact-mobile.png')});await inspector.getByRole('button',{name:'Prepare community assessment',exact:true}).click();const discard=page.getByRole('alertdialog',{name:'Discard unsaved changes?'});await discard.getByRole('button',{name:'Discard',exact:true}).click();const taskInspector=page.getByRole('dialog',{name:'Task details: Prepare community assessment'});await expect(taskInspector).toBeVisible();await expect(page.locator('[role=alertdialog]')).toHaveCount(0);await expect(taskInspector.getByRole('button',{name:'Close task detail'})).toBeFocused();await taskInspector.press('Escape');await expect(taskInspector).not.toBeVisible();await expect(page.getByRole('textbox',{name:'Search project Offices'})).toBeFocused();
});
test('Failed project invitation delivery still creates one invitation and fresh-link copy failure has manual recovery',async({page},info)=>{
 test.setTimeout(90_000);const r=await peopleFixture(page);r.projectOffices.push({id:'own',project_id:r.project,office_id:r.org,relationship_type:'lead',invitation_status:'joined'});r.organizations.push({id:partner,name:'Engineering Office',head_user_id:'foreign-head',is_active:true});const invites:any[]=[];let creates=0,rotations=0;
 await page.route('**/rest/v1/user_invitations?**',route=>{
  const query=new URL(route.request().url()).searchParams;
  expect(query.get('invitation_type')).toBe('eq.project_office');
  expect(query.get('select')).not.toMatch(/token|invitation_url|acceptance_claim/);
  const targets=(query.get('project_office_id')||'').slice(4,-1).split(',');
  return route.fulfill({json:invites.filter(invite=>targets.includes(invite.project_office_id))});
 });
 await page.route('**/controlpanelEflow/api/invitations/**',route=>{const path=new URL(route.request().url()).pathname;if(path.endsWith('/project-office')){creates++;const payload=route.request().postDataJSON();expect(payload.account_role).toBeUndefined();r.projectOffices.push({id:'partner',project_id:r.project,office_id:partner,relationship_type:payload.access,invitation_status:'pending',contact_email:payload.email});const item={id:'project-invite',project_office_id:'partner',invitation_type:'project_office',email:payload.email,account_role:'member',status:'pending',email_delivery_status:'failed',delivery_error:'Mail unavailable',expires_at:'2030-01-01'};invites.push(item);return route.fulfill({json:item});}if(path.endsWith('/resend')){rotations++;expect(route.request().postDataJSON()).toEqual({copy_link:true});return route.fulfill({json:{...invites[0],invitation_url:'synthetic-private-link'}});}return route.fulfill({json:{invitations:invites}});});
 await openOffices(page,r.project);await page.getByRole('button',{name:'Invite Office',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Let’s bring another Office in.'});await dialog.getByRole('combobox',{name:'Office',exact:true}).selectOption(partner);await dialog.getByLabel('Head / contact email').fill('engineering@example.test');await dialog.getByRole('button',{name:'Invite Office',exact:true}).click();await page.getByRole('alertdialog',{name:'Invite this Office?'}).getByRole('button',{name:'Invite Office',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Invitation created; email delivery failed');expect(creates).toBe(1);await expect(dialog.getByRole('button',{name:'Invite Office',exact:true})).toHaveCount(0);await dialog.getByRole('button',{name:'Done',exact:true}).click();
 await page.getByRole('button',{name:'Engineering Office',exact:true}).click();const inspector=page.getByRole('dialog',{name:'Engineering Office — project Office'});await inspector.getByRole('tab',{name:'Invitations',exact:true}).click();await expect(inspector).toContainText('Email: Failed');await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('Unavailable');}}}));await inspector.getByRole('button',{name:'Copy fresh link',exact:true}).click();await page.getByRole('alertdialog',{name:'Create a fresh invitation link?'}).getByRole('button',{name:'Create fresh link',exact:true}).click();await expect(inspector.getByRole('alert')).toContainText('Clipboard copy failed');await expect(inspector.getByLabel('Fresh invitation link')).toHaveValue('synthetic-private-link');expect(rotations).toBe(1);await inspector.getByRole('button',{name:'Hide link'}).click();await page.screenshot({path:info.outputPath('invitation-clipboard-recovery-no-link.png')});
});
for(const kind of ['observer','closed','governed'] as const)test(`Project Office ${kind} retains read-only reasons and governance handoff`,async({page},info)=>{
 test.setTimeout(90_000);const r=await peopleFixture(page);r.projectOffices.push({id:'own',project_id:r.project,office_id:r.org,relationship_type:kind==='observer'?'observer':'lead',invitation_status:'joined'});if(kind==='closed')r.projects[0].status='completed';if(kind==='governed')r.projects[0].source_collaboration_draft_id='60000000-0000-4000-8000-000000000001';
 await openOffices(page,r.project);const region=page.getByRole('region',{name:'Project Office collaboration'});await expect(region.getByRole('button',{name:'Select own members'})).toHaveCount(0);await region.getByRole('button',{name:'Planning Office',exact:true}).click();const inspector=page.getByRole('dialog',{name:'Planning Office — project Office'});await expect(inspector).toContainText(kind==='observer'?'Observers follow progress':kind==='closed'?'project is closed':'Proposal Context');await inspector.getByRole('tab',{name:'Project team',exact:true}).click();await expect(page.getByRole('dialog',{name:'Planning Office’s project team'}).getByRole('checkbox')).toHaveCount(0);await page.getByRole('dialog',{name:'Planning Office’s project team'}).press('Escape');await page.setViewportSize({width:320,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath(`office-${kind}-320.png`)});
});
test('Project Office read failure retries honestly and retains an inspector draft through refresh denial',async({page},info)=>{
 test.setTimeout(90_000);const r=await peopleFixture(page);r.projectOffices.push({id:'own',project_id:r.project,office_id:r.org,relationship_type:'lead',invitation_status:'joined'});let denied=true;
 await page.route('**/rest/v1/project_offices?**',route=>denied?route.fulfill({status:403,json:{message:'Office read denied'}}):route.fallback());
 await openOffices(page,r.project);const region=page.getByRole('region',{name:'Project Office collaboration'});await expect(region.getByRole('alert')).toContainText('Office read denied');await expect(region.getByText('No Office participation yet')).toHaveCount(0);denied=false;await region.getByRole('button',{name:'Retry',exact:true}).click();await region.getByRole('button',{name:'Select own members',exact:true}).click();const inspector=page.getByRole('dialog',{name:'Planning Office’s project team'});const person=inspector.getByRole('checkbox',{name:/Maria Santos/});await person.check();
 denied=true;await inspector.getByRole('button',{name:'Refresh participation',exact:true}).click();await expect(inspector.getByRole('alert')).toContainText('Office read denied');await expect(person).toBeChecked();await expect(person).toBeDisabled();denied=false;await inspector.getByRole('button',{name:'Retry',exact:true}).click();await expect(person).toBeEnabled();await expect(person).toBeChecked();await page.screenshot({path:info.outputPath('membership-draft-source-retry.png')});
 await inspector.press('Escape');await page.getByRole('alertdialog',{name:'Discard unsaved changes?'}).getByRole('button',{name:'Discard',exact:true}).click();await expect(inspector).not.toBeVisible();
});
