import {test,expect,type Page} from '@playwright/test';
import {projectWorkspaceFixture} from './fixtures/projectWorkspace';
async function invitationFixture(page:Page){
 const records=await projectWorkspaceFixture(page,'head',true,{compactLayout:true});const requests:any[]=[],submitted:any[]=[],mail:any[]=[];
 await page.route('**/rest/v1/rpc/r7_project_members',route=>route.fulfill({json:{kind:'office',members:[],offices:[]}}));
 await page.route('**/rest/v1/rpc/r8_*',async route=>{const operation=new URL(route.request().url()).pathname.split('/').at(-1);const args=route.request().postDataJSON();
  if(operation==='r8_list_requests')return route.fulfill({json:{kind:'office',office_id:records.org,timezone:'Asia/Singapore',can_request:true,requests}});
  if(operation==='r8_submit_request'){submitted.push(args);let item=requests.find(r=>r.id===args.p_id);if(!item){item={id:args.p_id,project_id:records.project,email:args.p_email,summary:args.p_summary,skills:args.p_skills,engagement:args.p_engagement,access_end:args.p_end,until_close:args.p_close,state:'pending',revision:1,invitation_created_at:null,delivery_status:'not_attempted',onboarding:'pending',pds_documents:[],can_approve:true,can_dispatch:false,can_revoke:true};requests.push(item);}return route.fulfill({json:item});}
  if(operation==='r8_decide_request'){const item=requests.find(r=>r.id===args.p_id);item.state=args.p_action;item.revision++;item.can_approve=false;item.can_dispatch=item.state==='approved';return route.fulfill({json:item});}
  return route.fulfill({json:[]});
 });
 await page.route(/\/project-invitations\/[^/]+\/dispatch$/,async route=>{mail.push(route.request().postDataJSON());const id=new URL(route.request().url()).pathname.split('/').at(-2);const item=requests.find(r=>r.id===id);item.invitation_created_at=new Date().toISOString();item.delivery_status='provider_accepted';item.revision++;return route.fulfill({json:{delivery_status:'provider_accepted',receipt:'Provider acceptance does not confirm mailbox delivery.'}});});
 await page.reload();await page.getByRole('button',{name:'Add view',exact:true}).click();await page.getByRole('dialog',{name:'Add project view'}).getByRole('button',{name:'Members',exact:true}).click();return {records,requests,submitted,mail};
}
test.beforeEach(()=>test.setTimeout(90000));
test('R8 request creates no dispatch and approval enables explicit sending',async({page})=>{
 const fixture=await invitationFixture(page);const panel=page.getByRole('region',{name:'Project Invitations'});await panel.getByRole('button',{name:'Invite by email · request Head approval'}).click();const dialog=page.getByRole('dialog',{name:'Request project members'});await dialog.getByLabel('Email address 1').fill('guest@example.test');await dialog.getByLabel('Requested skills').fill('Analysis, Planning');await dialog.getByRole('button',{name:'Submit requests for Head approval'}).click();await expect(dialog).toContainText('Request submitted');expect(fixture.mail).toHaveLength(0);expect(fixture.submitted[0].p_skills).toEqual(['Analysis','Planning']);await dialog.getByRole('button',{name:'Close request form'}).click();await expect(panel.getByRole('button',{name:'Create invitation and send email'})).toHaveCount(0);await panel.getByRole('button',{name:'Approve request'}).click();await panel.getByRole('button',{name:'Create invitation and send email'}).click();await expect(panel).toContainText('Email accepted by provider · receipt unconfirmed');expect(fixture.mail).toHaveLength(1);await expect(panel).toContainText('Pending acceptance');
});
test('R8 request form works at 320px in dark mode with no page overflow',async({page},info)=>{
 await page.setViewportSize({width:320,height:950});await invitationFixture(page);await page.evaluate(()=>document.documentElement.classList.add('dark'));await page.getByRole('button',{name:'Invite by email · request Head approval'}).click();const dialog=page.getByRole('dialog',{name:'Request project members'});await dialog.getByLabel('Email address 1').fill('guest@example.test');await dialog.getByLabel('Engagement').selectOption('OJT');await dialog.getByRole('checkbox',{name:'Until project completion or archive'}).uncheck();await expect(dialog.getByRole('button',{name:'Submit requests for Head approval'})).toBeDisabled();await dialog.getByLabel('Access ends after this date · Asia/Singapore').fill('2026-12-31');await expect(dialog.getByRole('button',{name:'Submit requests for Head approval'})).toBeEnabled();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);await page.screenshot({path:info.outputPath('r8-request-320.png'),fullPage:true});
});
for(const width of [1440,390])test(`R8 project guest acceptance preserves recipient and project scope at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.route('**/auth/v1/**',route=>route.fulfill({status:401,json:{message:'No session'}}));await page.routeWebSocket(/\/realtime\/v1\//,()=>{});await page.route('**/rest/v1/**',route=>route.fulfill({json:[]}));await page.route(/\/controlpanelEflow\//,route=>route.fulfill({json:{email:'guest@example.test',office_name:'Sponsoring Office',project_title:'Community assessment',project_id:'project',expires_at:'2026-12-31T00:00:00Z',existing_account:false,kind:'office',engagement:'OJT',until_close:true,skills:['Analysis'],summary:'Project research assistance'}}));
 await page.goto('/accept-project-invite?token='+'a'.repeat(43));await expect(page.getByRole('heading',{name:'Join Community assessment.'})).toBeVisible();await expect(page.getByLabel('Email',{exact:true})).toHaveValue('guest@example.test');await expect(page.getByLabel('Email',{exact:true})).toHaveAttribute('readonly','');await expect(page.getByText(/Your account role and Office affiliation stay unchanged/)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);expect(page.url()).not.toContain('token=');await page.screenshot({path:info.outputPath(`r8-accept-${width}.png`),fullPage:true});
});
test('R8 expired or revoked project links show recovery without account creation',async({page})=>{
 await page.route('**/auth/v1/**',route=>route.fulfill({status:401,json:{message:'No session'}}));await page.routeWebSocket(/\/realtime\/v1\//,()=>{});await page.route('**/rest/v1/**',route=>route.fulfill({json:[]}));await page.route(/\/controlpanelEflow\//,route=>route.fulfill({status:409,json:{detail:'Invitation expired, revoked or unavailable'}}));await page.goto('/accept-project-invite?token='+'a'.repeat(43));await expect(page.getByRole('heading',{name:'This invitation isn’t available.'})).toBeVisible();await expect(page.getByRole('button',{name:'Create account'})).toHaveCount(0);
});
