import {test,expect,type Page} from '@playwright/test';
import {projectWorkspaceFixture} from './fixtures/projectWorkspace';
async function fixture(page:Page,dark=false){
 const records=await projectWorkspaceFixture(page,'head',true,{compactLayout:true,theme:dark?'dark':'light'});let fingerprint='first',removed=false;const writes:any[]=[],offers:any[]=[];
 const member={user_id:'member',office:records.org,office_name:'Lead Office',project_office_id:'participation',name:'Selected person',engagement:'Permanent',access_end:null,until_close:false,access_ended_at:null,eligible:true,can_read:true,access:'member',state:'joined',responsibilities:[]};
 await page.route('**/rest/v1/rpc/r7_project_members',route=>route.fulfill({json:{kind:'office',timezone:'Asia/Singapore',members:removed?[{...member,eligible:false,can_read:false,access_ended_at:new Date().toISOString()}]:[member],offices:[]}}));
 await page.route('**/rest/v1/rpc/r9_*',async route=>{const name=new URL(route.request().url()).pathname.split('/').at(-1),args=route.request().postDataJSON();
  if(name==='r9_project_access')return route.fulfill({json:{kind:'office',open:true,can_share:true,timezone:'Asia/Singapore',grants:offers,can_remove_offices:[records.org],can_remove_personal:false}});
  if(name==='r9_removal_preview')return route.fulfill({json:{project:records.project,user:'member',office:records.org,fingerprint,tasks:[{id:'outside-page',title:'Assignment outside loaded page',status:'in_progress',lead:'member'}],nodes:[{id:'deep',root:'outside-page',title:'Deep descendant Lead',status:'for_review',lead:'member',people:['member']}]}});
  if(name==='r9_remove_person'){writes.push(args);if(args.p_fingerprint!==fingerprint)return route.fulfill({status:409,json:{code:'40001',message:'Assignments changed. Refresh impact preview.'}});removed=true;return route.fulfill({json:{removed:'member',project:records.project,tasks:1,nodes:1}});}
  if(name==='r9_grant_access'){const item={id:args.p_id,project_id:records.project,recipient:'recipient',name:'Verified recipient',email:args.p_email,office_id:records.org,access:args.p_access,engagement:args.p_engagement,access_end:args.p_end,until_close:args.p_access==='viewer'||args.p_close,redeemed_at:null,redeem_expires_at:new Date(Date.now()+args.p_ttl*86400000).toISOString(),effective:false,can_revoke:true,revoked_at:null};offers.push(item);return route.fulfill({json:item});}
  return route.fulfill({json:null});
 });await page.reload();return{records,writes,offers,changeImpact:()=>{fingerprint='changed';}};
}
async function members(page:Page){await page.getByRole('button',{name:'Add view',exact:true}).click();await page.getByRole('dialog',{name:'Add project view'}).getByRole('button',{name:'Members',exact:true}).click();}
test.beforeEach(()=>test.setTimeout(90000));
test('R9 creates a recipient-bound share offer with separate redemption and access terms',async({page},info)=>{
 const f=await fixture(page);await page.getByRole('button',{name:'Invite / share',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Share project'});await dialog.getByLabel('Existing verified recipient email').fill('recipient@example.test');await dialog.getByRole('combobox',{name:'Engagement',exact:true}).selectOption('OJT');await dialog.getByLabel('Access ends after this date · Asia/Singapore').fill('2026-12-31');await dialog.getByRole('button',{name:'Create share offer'}).click();await expect(dialog).toContainText('Share offer created');await expect(dialog).toContainText('Pending recipient redemption');expect(f.offers[0].access_end).toBe('2026-12-31T16:00:00.000Z');await expect(dialog.getByLabel('Recipient project link')).toHaveValue(/\/project-share\?grant=/);await expect(dialog.getByRole('button',{name:'Copy navigation link'})).toBeVisible();await page.screenshot({path:info.outputPath('r9-share-desktop.png'),fullPage:true});
});
test('R9 cancellation makes no write; confirmation removes complete server impact',async({page})=>{
 const f=await fixture(page);await members(page);await page.getByRole('button',{name:'Review removal · Selected person'}).click();let dialog=page.getByRole('dialog',{name:'Review removal · Selected person'});await expect(dialog).toContainText('Assignment outside loaded page');await expect(dialog).toContainText('Deep descendant Lead');await dialog.getByRole('button',{name:'Cancel removal'}).click();expect(f.writes).toHaveLength(0);await page.getByRole('button',{name:'Review removal · Selected person'}).click();dialog=page.getByRole('dialog',{name:'Review removal · Selected person'});await expect(dialog).toContainText('Deep descendant Lead');await dialog.getByRole('button',{name:'Confirm removal and unassign work'}).click();await expect(dialog).toContainText('Removal saved');expect(f.writes).toHaveLength(1);await dialog.getByRole('button',{name:'Done',exact:true}).click();await expect(page.getByRole('table',{name:'Selected project members'})).toContainText('Ended');
});
test('R9 concurrent assignment conflict requires a refreshed preview at 320px in dark mode',async({page},info)=>{
 await page.setViewportSize({width:320,height:950});await page.emulateMedia({colorScheme:'dark'});const f=await fixture(page,true);await members(page);await page.getByRole('button',{name:'Review removal · Selected person'}).click();const dialog=page.getByRole('dialog',{name:'Review removal · Selected person'});await expect(dialog).toContainText('Deep descendant Lead');await expect(dialog).toHaveCSS('background-color','rgb(20, 46, 42)');f.changeImpact();await dialog.getByRole('button',{name:'Confirm removal and unassign work'}).click();await expect(dialog).toContainText('Assignments changed');await dialog.getByRole('button',{name:'Refresh impact preview'}).click();await expect(dialog.getByRole('button',{name:'Confirm removal and unassign work'})).toBeEnabled();await page.screenshot({path:info.outputPath('r9-removal-320.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);await dialog.getByRole('button',{name:'Confirm removal and unassign work'}).click();await expect(dialog).toContainText('Removal saved');expect(f.writes.map(w=>w.p_fingerprint)).toEqual(['first','changed']);
});
test('R9 revoked or wrong-recipient shares fail after verified sign-in',async({page})=>{
 await fixture(page);await page.route('**/rest/v1/rpc/r9_open_share',route=>route.fulfill({status:403,json:{code:'42501',message:'Share expired, revoked or belongs to another recipient'}}));await page.goto('/project-share?grant=00000000-0000-4000-8000-000000005000');await expect(page.getByRole('heading',{name:'This project share is unavailable.'})).toBeVisible();await expect(page.getByText('Share expired, revoked or belongs to another recipient')).toBeVisible();
});
