import { Check, Send } from "lucide-react";
import { DemoAction, DemoBadge, DemoCard, DemoChecks, DemoConfirmation, DemoField, type DemoScreenProps } from "./PreviewControls";
import styles from "../WorkflowDemo.module.scss";

export function ApprovalScreens(props: DemoScreenProps) {
  const { step, kind } = props;
  if (step.screen === "publish-confirm") return <DemoConfirmation {...props} title="Publish this work plan?" id="publish-confirm" action="Publish work plan"><p>The proposed projects, tasks, staff assignments, and funded task allocations become active.</p><DemoChecks labels={["Plan checked", "Team and budget ready", ...(kind === "interdepartmental" ? ["Required participation approvals received"] : [])]} /></DemoConfirmation>;
  if (step.screen === "publish") return <DemoCard title="Ready to publish"><DemoChecks labels={["Work plan saved", "Task departments and schedules set", "Yearly budget locked and task budgets valid", ...(kind === "interdepartmental" ? ["Required offices approved the updated plan"] : [])]} /><div className={styles.cardFooter}><span>{kind === "interdepartmental" ? "Participation approval is complete." : "Department-only proposal"}</span><DemoAction {...props} id="publish"><Send size={15} /> {kind === "interdepartmental" ? "Publish proposal" : "Publish department proposal"}</DemoAction></div></DemoCard>;
  if (step.screen === "plan-inbox") return <DemoCard title="Work Plan Review"><DemoBadge tone="amber">Needs Decision</DemoBadge><h4>Community Services Improvement</h4><p>Lead Department · Incoming participation request</p><div className={styles.cardFooter}><span>Open the saved proposal to decide participation.</span><DemoAction {...props} id="plan-inbox">Review &amp; Governance</DemoAction></div></DemoCard>;
  if (step.screen === "participation-confirm") return <DemoConfirmation {...props} title="Approve participation" action="Confirm decision" id="participation-confirm"><DemoField label="Acting on behalf of" value="Office B" /><DemoField label="Approval note (optional)" value="Office responsibilities and staffing reviewed." /><p>Confirm agreement to this saved work plan.</p></DemoConfirmation>;
  if (step.screen === "participation") return <DemoCard title="Department participation decision"><p>Acting on behalf of: <strong>Office B</strong></p><div className={styles.requestSummary}><span>Office responsibility</span><strong>Support community visits</strong><span>Proposed team</span><strong>1 task leader · 2 members</strong><span>Saved plan</span><strong>Current version · For review</strong></div><div className={styles.cardFooter}><span className={styles.feedbackOption}>Request changes · Decline</span><DemoAction {...props} id="participation"><Check size={15} /> Approve participation</DemoAction></div></DemoCard>;
  if (step.screen === "request-confirm") return <DemoConfirmation {...props} title="Send this plan for review?" action="Send for review" id="request-confirm"><p>Participating departments will be notified to review the latest saved plan and confirm participation.</p></DemoConfirmation>;
  if (step.screen === "request" || step.screen === "resend") {
    const resend = step.screen === "resend";
    return <>
      {resend && <div className={styles.notice}><strong>Updates needed · Office B</strong><span>“Please update the team and visit schedule.”</span><small>Corrections saved · Updated plan ready for review</small></div>}
      <DemoCard title="Department approval table"><div className={styles.approvalTable}><div className={styles.approvalHeader}><span>Department</span><span>Role</span><span>Approval</span></div><div><strong>Lead Department</strong><span>Owner</span><DemoBadge tone="gray">Lead</DemoBadge></div>{["Office A", "Office B", "Review Board"].map((office) => <div key={office}><strong>{office}</strong><span>{office === "Review Board" ? "Governance reviewer" : "Required participant"}</span><DemoBadge tone={resend ? "amber" : "gray"}>{resend ? "Review updated plan" : "Not requested"}</DemoBadge></div>)}</div><div className={styles.cardFooter}><span>Requests use the latest saved plan.</span><DemoAction {...props} id={step.screen}><Send size={15} /> {resend ? "Resend approval requests" : "Send approval requests"}</DemoAction></div></DemoCard>
      <DemoCard title="Approval status"><p>Publication waits for required offices to approve the current plan and clear unresolved update requests.</p></DemoCard>
    </>;
  }
  return null;
}
