import { Banknote, Check, LockKeyhole, Send } from "lucide-react";
import { DemoAction, DemoBadge, DemoCard, DemoChecks, DemoConfirmation, DemoField, DemoFile, type DemoScreenProps } from "./PreviewControls";
import styles from "../WorkflowDemo.module.scss";

export function BudgetScreens(props: DemoScreenProps) {
  switch (props.step.screen) {
    case "annual-budget": return <>
      <DemoCard title="Annual office budget"><DemoBadge tone="amber">Draft · FY 2026</DemoBadge><p>The Head defines the annual envelope. Published proposals reserve funds from the locked total.</p><DemoField label="Annual spending authority" value="₱1,000,000.00" /></DemoCard>
      <DemoCard title="Cash release and liquidation controls"><DemoField label="Daily cash release ceiling" value="₱10,000.00" /><DemoField label="Per-receipt review threshold" value="₱5,000.00" /><DemoField label="Liquidation due after release (days)" value="15" /><div className={styles.cardFooter}><span>Example amounts · Save draft is also available</span><DemoAction {...props} id="annual-budget"><LockKeyhole size={14} /> Save &amp; lock annual budget</DemoAction></div></DemoCard>
    </>;
    case "lock-budget": return <DemoConfirmation {...props} title="Lock the 2026 office budget?" action="Confirm budget lock" id="lock-budget"><DemoField label="Annual total" value="₱1,000,000.00" /><p>Review the yearly amount and controls first. The original appropriation cannot be edited after locking.</p><DemoChecks labels={["Authorized yearly amount entered", "Cash controls reviewed"]} /></DemoConfirmation>;
    case "proposal-budget": return <DemoCard title="Proposal budget"><DemoField label="Task" value="Prepare outreach materials · Lead Office" /><DemoField label="Budget decision" value="Funded" /><DemoField label="Budget line and fund source" value="Supplies · Printing materials · Office appropriation" /><DemoField label="Proposed task budget" value="₱5,000.00" /><DemoChecks labels={["Yearly office budget is locked", "Available annual authority covers this proposal"]} /><div className={styles.cardFooter}><span>No-cost tasks require their recorded reason.</span><DemoAction {...props} id="proposal-budget">Continue</DemoAction></div></DemoCard>;
    case "funding": return <DemoCard title="Community Services Improvement"><DemoBadge>Reserved at publication</DemoBadge><div className={styles.amountRow}><span>Proposal commitment</span><strong>₱5,000.00</strong></div><div data-preview-target="funding"><div className={styles.amountRow}><span>Prepare outreach materials · Task Leader</span><strong>₱5,000.00</strong></div><DemoChecks labels={["Task funding allocation created", "Printing budget line available for requests"]} /><p>Reserved: ₱0.00 · Spent: ₱0.00 · Remaining: ₱5,000.00</p></div></DemoCard>;
    case "cash-request": return <DemoCard title="Task funding · What needs to be purchased?"><DemoBadge>Approved task budget: ₱5,000.00</DemoBadge><DemoField label="Proposal budget line and fund source" value="Supplies · Printing materials · Office appropriation" /><DemoField label="Amount" value="₱5,000.00" /><DemoField label="Needed by" value="Oct 9 · Must not be earlier than today" /><DemoField label="Purchase and purpose" value="Print information sheets for community outreach." /><div className={styles.cardFooter}><span>Leader’s own request → Head / Member</span><DemoAction {...props} id="cash-request"><Send size={14} /> Request cash</DemoAction></div></DemoCard>;
    case "cash-authorize": return <DemoCard title="Cash requests"><DemoBadge tone="amber">Fiscal authorization pending</DemoBadge><h4>FR-00001 · Prepare outreach materials</h4><p>Task Leader · Printing information sheets · ₱5,000.00</p><DemoChecks labels={["Locked yearly budget", "Funded task allocation", "Amount held within available task funds"]} /><p className={styles.smallNote}>Button wording is Quick Authorize or Authorize according to the configured approval threshold. Member requests first need leader endorsement.</p><div className={styles.cardFooter}><span>Return with a reason if corrections are needed.</span><DemoAction {...props} id="cash-authorize">Quick Authorize</DemoAction></div></DemoCard>;
    case "release": return <DemoCard title="Voucher & release schedule"><DemoBadge tone="amber">Scheduled</DemoBadge><DemoField label="Recipient" value="Task Leader" /><DemoField label="Request / task" value="PC-00001 · Prepare outreach materials" /><DemoField label="Scheduled amount" value="₱5,000.00 · Oct 9" /><div className={styles.cardFooter}><span>Daily cash ceiling remains enforced.</span><DemoAction {...props} id="release"><Banknote size={14} /> Mark released</DemoAction></div></DemoCard>;
    case "voucher": return <DemoConfirmation {...props} title="Disbursement Voucher" action="Confirm & Record Release" id="voucher"><p>Voucher number</p><div className={styles.voucherCode}>DV-2026-00001-A3F1</div><DemoField label="Recipient / amount" value="Task Leader · ₱5,000.00" /><DemoField label="Release method" value="Cash handover (or cheque issuance)" /><DemoChecks labels={["Cash physically handed over to the recipient"]} /><p>Cheque releases also require the cheque number.</p></DemoConfirmation>;
    case "acknowledge": return <DemoCard title="Task funding · Funding activity"><DemoBadge>Released</DemoBadge><DemoField label="Request / received amount" value="FR-00001 · ₱5,000.00" /><DemoField label="Cash recipient" value="Task Leader" /><div className={styles.cardFooter}><span>Recipient acknowledgment is pending.</span><DemoAction {...props} id="acknowledge">Acknowledge cash</DemoAction></div></DemoCard>;
    case "receipt-confirm": return <DemoConfirmation {...props} title="Confirm Cash Receipt" action="Confirm Receipt" id="receipt-confirm"><p>Enter the Disbursement Voucher number provided by the releasing officer.</p><DemoField label="Voucher Number" value="DV-2026-00001-A3F1" /><DemoBadge>Voucher matches</DemoBadge><DemoField label="Amount / recipient" value="₱5,000.00 · Task Leader" /></DemoConfirmation>;
    case "receipts": return <DemoCard title="Upload receipts and return balance"><DemoBadge>Released ₱5,000.00 · Unused cash ₱200.00</DemoBadge><DemoField label="Actual amount spent / receipt total" value="₱4,800.00 / ₱4,800.00" /><DemoField label="Vendor / expense / receipt number" value="Local Print Shop · Information sheets · OR-001" /><DemoFile name="Printing-receipt.pdf" /><DemoField label="Official refund receipt number / cash return date" value="REF-001 · Oct 12" /><DemoField label="Liquidation note" value="Materials printed; ₱200.00 unused cash returned." /><div className={styles.cardFooter}><span>Receipt corrections create a new version.</span><DemoAction {...props} id="receipts">Submit liquidation</DemoAction></div></DemoCard>;
    case "settlement": return <DemoCard title="Accounting settlement queue"><DemoBadge tone="amber">Pending office settlement · On time</DemoBadge><p>FR-00001 · Task Leader · Prepare outreach materials</p><DemoFile name="Printing-receipt.pdf" /><div className={styles.amountRow}><span>Expense</span><strong>₱4,800.00</strong></div><div className={styles.amountRow}><span>Returned · Refund OR REF-001</span><strong>₱200.00</strong></div><DemoChecks labels={["Receipt evidence verified", "Returned balance verified"]} /><p className={styles.smallNote}>Leader’s own receipts skip self-endorsement. Member receipts first go to Leader Reviews → Budget. Accounting cannot settle late packages; the Head must approve them.</p><div className={styles.cardFooter}><span>Request changes if receipts need corrections.</span><DemoAction {...props} id="settlement"><Check size={14} /> Settle &amp; post</DemoAction></div></DemoCard>;
    default: return null;
  }
}

