import { Archive, Check } from "lucide-react";
import { DemoAction, DemoBadge, DemoCard, DemoChecks, DemoConfirmation, DemoField, type DemoScreenProps } from "./PreviewControls";
import styles from "../WorkflowDemo.module.scss";

export function CloseoutScreens(props: DemoScreenProps) {
  const inter = props.kind === "interdepartmental";
  switch (props.step.screen) {
    case "closeout": return <DemoCard title={inter ? "Final governance closeout" : "Proposal project completion"}><DemoChecks labels={["All tasks approved or properly cancelled", "Subtask evidence approved", "Task and subtask funds cleared"]} />{inter && <DemoField label="Closeout note" value="Completed outreach records, evidence, and settled funds are ready for verification." />}<div className={styles.cardFooter}><span>{inter ? "Governance reviewers configured for this example" : "No external office approval required"}</span><DemoAction {...props} id="closeout">{inter ? "Send closeout to governance" : "Continue"}</DemoAction></div></DemoCard>;
    case "closeout-approve": return <DemoCard title="Your final closeout decision"><DemoBadge tone="amber">Pending final verification</DemoBadge><DemoChecks labels={["All proposal tasks resolved", "Evidence and financial records checked"]} /><DemoField label="Board resolution number (optional)" value="RES-2026-001" /><DemoField label="Meeting date" value="Oct 20" /><DemoField label="Endorsement or required correction" value="Final proposal records verified." /><div className={styles.cardFooter}><span>Request correction · Decline</span><DemoAction {...props} id="closeout-approve">Approve closeout</DemoAction></div></DemoCard>;
    case "complete": return inter ? <DemoCard title="Governance verification complete"><DemoChecks labels={["Required final approvals received", "Work and cash checks passed"]} /><DemoField label="Completion note (optional)" value="Completed proposal verified and ready to retain." /><p>Complete every linked operational project together.</p><div className={styles.cardFooter}><span>Review the confirmation before proceeding.</span><DemoAction {...props} id="complete">Mark proposal completed</DemoAction></div></DemoCard> : <DemoCard title="All delivery tasks are approved"><DemoChecks labels={["Linked project completion checks passed", "Task and subtask funds cleared"]} /><p>Complete the linked operational projects together.</p><div className={styles.cardFooter}><span>Individual projects also have their own completion dialog.</span><DemoAction {...props} id="complete">Mark projects completed</DemoAction></div></DemoCard>;
    case "archive": return inter ? <DemoCard title="Proposal is completed"><DemoBadge>Completed</DemoBadge><DemoField label="Archive reason (required)" value="Completed work retained for reporting and audit." /><p>Archiving removes the linked projects and tasks from active workspaces. Review the confirmation first.</p><div className={styles.cardFooter}><span>Proposal, decisions, evidence, and audit records remain.</span><DemoAction {...props} id="archive">Archive proposal delivery</DemoAction></div></DemoCard> : <DemoConfirmation {...props} title="Archive all completed operational projects?" action="Archive delivery" id="archive"><DemoBadge>Completed</DemoBadge><p>Governance history and audit logs remain intact. All linked projects and tasks leave active workspaces.</p></DemoConfirmation>;
    case "archived": return <>
      <DemoCard title="Archived projects"><article className={styles.archivedRecord} data-preview-target="archived"><div className={styles.emptyIcon}><Archive size={25} /></div><div><DemoBadge tone="gray">Archived</DemoBadge><h4>Community Services Improvement</h4><p>Lead Department · Work completed</p><div className={styles.retained}><Check size={13} /> Evidence retained <Check size={13} /> Approval history retained</div></div></article></DemoCard>
      <DemoCard title="Project history"><div className={styles.history}>{["Proposal published and task funding reserved", "Voucher released and acknowledged", "Receipts settled", "Subtask evidence approved", "Task completion approved", "Project completed", "Project archived"].map((event) => <div key={event}><Check size={14} /><span>{event}</span></div>)}</div></DemoCard>
    </>;
    default: return null;
  }
}
