import { Check, Plus, Send } from "lucide-react";
import { DemoAction, DemoBadge, DemoCard, DemoChecks, DemoConfirmation, DemoField, DemoFile, type DemoScreenProps } from "./PreviewControls";
import styles from "../WorkflowDemo.module.scss";

function SubtaskHeader() {
  return <div className={styles.drawerHeading}><h3>Draft the information sheet</h3><small>Subtask of: Prepare outreach materials · Reviewer: Task Leader · Lead Office</small></div>;
}

export function TaskScreens(props: DemoScreenProps) {
  const { step } = props;
  switch (step.screen) {
    case "tasks": return <>
      <div className={styles.stats}><DemoCard title="Leading Tasks"><strong className={styles.stat}>1</strong></DemoCard><DemoCard title="Active Work"><strong className={styles.stat}>1</strong></DemoCard><DemoCard title="Awaiting Your Review"><strong className={styles.stat}>0</strong></DemoCard></div>
      <DemoCard title="Prepare outreach materials"><div className={styles.taskMetadata}><DemoBadge>You’re Lead</DemoBadge><DemoBadge tone="gray">To Do</DemoBadge><span>Lead Office · 3 working days · Due Oct 12</span></div><p>Task members: Task Leader and Team Member</p><div className={styles.cardFooter}><span>Project: Community Services Improvement</span><DemoAction {...props} id="tasks">View Details</DemoAction></div></DemoCard>
    </>;
    case "start-task": return <DemoCard title="Prepare outreach materials"><DemoBadge tone="gray">To Do</DemoBadge><DemoField label="Task Leader" value="Task Leader · Lead Office" /><DemoField label="Deadline" value="Oct 12 · 3 working days" /><p>This task is ready to begin.</p><div className={styles.cardFooter}><span>Parent progress is calculated from approved work.</span><DemoAction {...props} id="start-task">Start work</DemoAction></div></DemoCard>;
    case "assign-subtasks": return <DemoCard title="Subtasks"><DemoField label="Subtask title" value="Draft the information sheet" /><DemoField label="Assigned contributor" value="Team Member · Lead Office" /><DemoField label="Reviewer" value="Task Leader" /><DemoField label="Deadline" value="Oct 10" /><DemoBadge tone="gray">Standalone · No prerequisite</DemoBadge><div className={styles.cardFooter}><span>Only task members can be assigned.</span><DemoAction {...props} id="assign-subtasks"><Plus size={14} /> Add</DemoAction></div></DemoCard>;
    case "my-subtasks": return <DemoCard title="Prepare outreach materials"><div className={styles.officeRow}><div><strong>Draft the information sheet</strong><small>Assigned to Team Member · Due Oct 10 · Reviewer: Task Leader</small></div><DemoBadge tone="gray">Pending</DemoBadge></div><div className={styles.cardFooter}><span>Subtasks are grouped by their parent task.</span><DemoAction {...props} id="my-subtasks">Draft the information sheet</DemoAction></div></DemoCard>;
    case "progress": return <DemoCard title="Assigned subtask"><SubtaskHeader /><div className={styles.workProgress}><span>Subtask progress</span><strong>75%</strong><div><span /></div></div><DemoField label="Work note" value="Information sheet drafted; checking final wording." /><DemoField label="Blocker" value="None" /><DemoField label="Next step" value="Finish and submit evidence to the Task Leader." /><DemoFile name="Information-sheet-draft.pdf" /><div className={styles.cardFooter}><span>Progress is reported by the assigned contributor.</span><DemoAction {...props} id="progress">Save update</DemoAction></div></DemoCard>;
    case "subtask-submit": return <DemoCard title="Complete assigned subtask"><SubtaskHeader /><DemoField label="Subtask progress" value="100%" /><DemoField label="Completion note (required)" value="Information sheet finalized and checked." /><DemoFile name="Final-information-sheet.pdf" /><DemoChecks labels={["Completion note supplied", "At least one evidence file supplied"]} /><div className={styles.cardFooter}><span>100% reported · Approval still pending</span><DemoAction {...props} id="subtask-submit"><Send size={14} /> Submit for review</DemoAction></div></DemoCard>;
    case "subtasks": return <div className={styles.queue}><aside className={styles.queueList}><strong>Draft the information sheet</strong><small>Team Member · Prepare outreach materials</small><DemoBadge tone="amber">For Review</DemoBadge></aside><DemoCard title="Subtask evidence · Attempt 1"><SubtaskHeader /><p>Submitted by Team Member: “Information sheet finalized and checked.”</p><DemoFile name="Final-information-sheet.pdf" /><DemoField label="Feedback (required when requesting changes)" value="Evidence checked against the completion standard." /><div className={styles.cardFooter}><span>Request changes</span><DemoAction {...props} id="subtasks"><Check size={14} /> Approve evidence</DemoAction></div></DemoCard></div>;
    case "submit": return <DemoCard title="Ready for review?"><DemoChecks labels={["All subtasks approved"]} /><DemoField label="Completion note" value="Outreach materials completed and distributed." /><DemoFile name="Completed-outreach-materials.pdf" /><div className={styles.cardFooter}><span>Add evidence · Submit the parent task</span><DemoAction {...props} id="submit"><Send size={14} /> Submit for review</DemoAction></div></DemoCard>;
    case "review": return <div className={styles.queue}><aside className={styles.queueList}><strong>Prepare outreach materials</strong><small>Submitted by Task Leader</small><DemoBadge tone="amber">For Review</DemoBadge></aside><DemoCard title="Task submission"><p>Prepare outreach materials · Lead Office</p><DemoFile name="Completed-outreach-materials.pdf" /><DemoChecks labels={["Subtask evidence approved", "Completion evidence checked", "Cash clearance: no open task or subtask funds"]} /><div className={styles.cardFooter}><span>Request changes with feedback</span><DemoAction {...props} id="review"><Check size={14} /> Approve</DemoAction></div></DemoCard></div>;
    case "review-confirm": return <DemoConfirmation {...props} title="Approve this task?" action="Confirm approval" id="review-confirm"><DemoChecks labels={["Evidence checked", "Cash clearance passed"]} /><DemoField label="Approval note (optional)" value="Completed work verified." /><p>Approval marks Prepare outreach materials completed.</p></DemoConfirmation>;
    default: return null;
  }
}

