import { useCallback, useEffect, useState } from 'react';
import { MoreHorizontal, Plus, Search, UserRound } from 'lucide-react';
import { WorkspaceHeader, WorkspaceTabs, StatusPill, ActionMenu } from '../../../components/ui/workspace';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '../../../components/ui/dialog';
import { InviteMemberDialog, listInvitations, resendInvitation, revokeInvitation, type Invitation } from '../../invitations';
import { ProfessionalProfilePanel, uploadPds } from '../../professional-profile';
import { phase2Request } from '../../../shared/phase2Api';
import '../officeTeam.css';

interface Member { id: string; full_name: string; email: string; role: string; is_active: boolean; }
const roleLabel = (role: string) => ({ head: 'Head', member: 'Member', accounting_staff: 'Accounting Staff' }[role] || role);
export function OfficeTeamWorkspace() {
  const [members, setMembers] = useState<Member[]>([]); const [invitations, setInvitations] = useState<Invitation[]>([]); const [office, setOffice] = useState('your Office');
  const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all'); const [tab, setTab] = useState('active'); const [dialog, setDialog] = useState(false); const [detail, setDetail] = useState<Member>();
  const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string>();
  const refresh = useCallback(async () => {
    const [team, pending] = await Promise.all([phase2Request<{ office_name: string; members: Member[] }>('/office-team'), listInvitations()]);
    setMembers(team.members); setOffice(team.office_name); setInvitations(pending.invitations);
  }, []);
  useEffect(() => { void refresh().catch(reason => setError(reason.message)).finally(() => setLoading(false)); }, [refresh]);
  const matches = (email: string, role: string, name = '') => `${email} ${name}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || role === filter);
  async function manage(id: string, action: 'resend' | 'copy' | 'revoke') { setBusy(id); setError(''); try {
    if (action === 'revoke') await revokeInvitation(id);
    else { const result = await resendInvitation(id, action === 'copy'); if (result.invitation_url) await navigator.clipboard.writeText(result.invitation_url); if (result.delivery_error) setError(result.delivery_error); }
    await refresh();
  } catch (reason) { setError((reason as Error).message); } finally { setBusy(undefined); } }
  const pendingRows = invitations.filter(item => item.status !== 'accepted' && matches(item.email, item.account_role));
  return <section className="eflow-office-team" aria-label="Office Team" data-tour-id="office-team"><WorkspaceHeader title="Office Team" description={`Good work starts with your people. Build your team in ${office}.`} actions={<button className="eflow-primary-button" onClick={() => setDialog(true)} data-tour-id="invite-member"><Plus size={17} /> Invite Member</button>} />
    <div className="eflow-team-toolbar"><label><Search size={16} /><span className="sr-only">Search Office Team</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search your team" /></label><label><span className="sr-only">Filter by account role</span><select value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All roles</option><option value="member">Member</option><option value="accounting_staff">Accounting Staff</option></select></label></div>
    {error && <p role="alert" className="eflow-form-error">{error}</p>}{loading ? <p role="status">Loading your Office Team…</p> : <WorkspaceTabs value={tab} onValueChange={setTab} label="Office Team views" tabs={[
      { id: 'active', label: `Active Members (${members.filter(member => member.is_active).length})`, content: <div className="eflow-team-table-wrap"><table className="eflow-team-table"><thead><tr><th scope="col">Name</th><th scope="col">Email</th><th scope="col">Role</th><th scope="col">Status</th></tr></thead><tbody>{members.filter(member => member.is_active && matches(member.email, member.role, member.full_name)).map(member => <tr key={member.id}><th scope="row"><button className="eflow-member-link" onClick={() => setDetail(member)}><span className="eflow-team-avatar"><UserRound size={17} /></span>{member.full_name}</button></th><td>{member.email}</td><td>{roleLabel(member.role)}</td><td><StatusPill label="Active" tone="positive" /></td></tr>)}</tbody></table>{!members.length && <p className="p-6">Invite someone to start building your Office Team.</p>}</div> },
      { id: 'pending', label: `Pending Invitations (${invitations.filter(item => ['pending', 'expired'].includes(item.status)).length})`, content: pendingRows.length ? <div className="eflow-team-table-wrap"><table className="eflow-team-table"><thead><tr><th scope="col">Email</th><th scope="col">Role</th><th scope="col">Status</th><th scope="col">Invited</th><th scope="col">Actions</th></tr></thead><tbody>{pendingRows.map(item => <tr key={item.id}><th scope="row">{item.email}</th><td>{roleLabel(item.account_role)}</td><td><StatusPill label={item.status === 'pending' ? 'Pending' : item.status === 'expired' ? 'Expired' : 'Revoked'} tone={item.status === 'revoked' ? 'negative' : 'warning'} />{item.pds_documents?.map(document => <span key={document.id} className="eflow-invite-help block">PDS: {document.processing_status}</span>)}{item.email_delivery_status === 'failed' && <span className="eflow-delivery-failed">Email failed · retry send</span>}</td><td>{new Date(item.created_at).toLocaleDateString()}</td><td>{['pending', 'expired'].includes(item.status) && <><ActionMenu trigger={<button className="eflow-icon-button" aria-label={`Manage invitation for ${item.email}`} disabled={busy === item.id}><MoreHorizontal size={19} /></button>} actions={[{ id: 'resend', label: 'Resend invitation', onSelect: () => void manage(item.id, 'resend') }, { id: 'copy', label: 'Copy fresh link (replaces old link)', onSelect: () => void manage(item.id, 'copy') }, { id: 'revoke', label: 'Revoke invitation', onSelect: () => void manage(item.id, 'revoke') }]} /><label className="eflow-text-button eflow-invite-help">Attach PDS<input type="file" className="eflow-small-file" aria-label={`Attach PDS for ${item.email}`} accept=".pdf,application/pdf" disabled={busy === item.id} onChange={async event => { const file = event.target.files?.[0]; if (!file) return; setBusy(item.id); try { await uploadPds(file, item.id); await refresh(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(undefined); } }} /></label></>}</td></tr>)}</tbody></table></div> : <div className="eflow-team-empty"><UserRound size={32} /><h2>Your next teammate starts here.</h2><p>Invite people by email. They’ll create their own account and join your Office.</p><button className="eflow-primary-button" onClick={() => setDialog(true)}>Invite Member</button></div> },
    ]} />}
    <InviteMemberDialog officeName={office} open={dialog} onOpenChange={setDialog} onSent={() => { setTab('pending'); void refresh().catch(reason => setError(reason.message)); }} />
    <Dialog open={Boolean(detail)} onOpenChange={value => { if (!value) setDetail(undefined); }}><DialogContent className="eflow-member-panel"><DialogTitle>{detail?.full_name}</DialogTitle><DialogDescription>{detail && roleLabel(detail.role)} · {office} · Active</DialogDescription>{detail && <ProfessionalProfilePanel userId={detail.id} />}</DialogContent></Dialog>
  </section>;
}
