// @vitest-environment jsdom
import { act, cleanup, renderHook } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { Task } from '../../src/app/features/tasks';
const calls=vi.hoisted(()=>({context:vi.fn(),recommend:vi.fn(),assign:vi.fn()}));
vi.mock('../../src/app/features/tasks',()=>({assignTask:calls.assign}));
vi.mock('../../src/app/features/staffing/services/staffingService',async original=>({...await original<Record<string,unknown>>(),fetchStaffingContext:calls.context,recommendStaff:calls.recommend}));
import { useStaffingReview } from '../../src/app/features/staffing/hooks/useStaffingReview';
const candidate={id:'m',name:'Maria',skills:['Planning'],training:[],education:[],experience:[],specializations:[],certifications:[],experience_summary:'',activeTasks:2,remainingHours:8,unknownEffortTasks:1};
const context={task:{id:'t',title:'Assess'},candidates:[candidate],excludedUnconfirmed:2};const task={id:'t',title:'Assess',teamMemberIds:[]} as unknown as Task;
beforeEach(()=>{vi.clearAllMocks();calls.context.mockResolvedValue(context);calls.recommend.mockResolvedValue([{userId:'m',evidence:['Planning'],activeTasks:2,remainingHours:8,unknownEffortTasks:1}]);calls.assign.mockResolvedValue(undefined);});afterEach(cleanup);
describe('Phase 15 advisory staffing authority',()=>{
 it('does not assign on generation or canceled review and refreshes eligibility before explicit assignment',async()=>{const view=renderHook(()=>useStaffingReview(task));await act(async()=>{});await act(async()=>view.result.current.generate());expect(calls.assign).not.toHaveBeenCalled();act(()=>view.result.current.setSelected('m'));await act(async()=>view.result.current.confirm(async()=>false));expect(calls.assign).not.toHaveBeenCalled();await act(async()=>view.result.current.confirm(async()=>true));expect(calls.context).toHaveBeenCalledTimes(3);expect(calls.assign).toHaveBeenCalledOnce();});
 it('retains the selected recommendation after denial and blocks assignment when the candidate disappears',async()=>{const view=renderHook(()=>useStaffingReview(task));await act(async()=>{});await act(async()=>view.result.current.generate());act(()=>view.result.current.setSelected('m'));calls.context.mockRejectedValueOnce(new Error('Authority revoked'));await act(async()=>view.result.current.confirm(async()=>true));expect(view.result.current.selected).toBe('m');expect(view.result.current.error).toContain('revoked');expect(calls.assign).not.toHaveBeenCalled();calls.context.mockResolvedValueOnce({...context,candidates:[]});await act(async()=>view.result.current.confirm(async()=>true));expect(calls.assign).not.toHaveBeenCalled();expect(view.result.current.error).toContain('No recommendations');});
 it('deduplicates assignment and preserves a successful receipt after a caller refresh fails',async()=>{const view=renderHook(()=>useStaffingReview(task,()=>{throw new Error('Refresh');}));await act(async()=>{});await act(async()=>view.result.current.generate());act(()=>view.result.current.setSelected('m'));let a!:Promise<void>;act(()=>{a=view.result.current.confirm(async()=>true);void view.result.current.confirm(async()=>true);});await act(async()=>{await a;await view.result.current.confirm(async()=>true);});expect(calls.assign).toHaveBeenCalledOnce();expect(view.result.current.saved).toBe(true);await act(async()=>view.result.current.confirm(async()=>true));expect(calls.assign).toHaveBeenCalledOnce();expect(view.result.current.error).toContain('Owner assigned');});
});
