import { useState } from "react";
import type { DepartmentBudgetBundle } from "../types";
import { buildPettyCashVoucherRows,PCV_HEADINGS } from "../selectors/pettyCashVoucherReport";
import { downloadBudgetCsv,printBudgetTable } from "../services/budgetReportExport";
import { peso } from "./budgetUi";
export function PettyCashVoucherRegister({data}:{data:DepartmentBudgetBundle}) {
  const [verifiedOnly,setVerifiedOnly]=useState(true),[query,setQuery]=useState("");
  const filtered={...data,requests:data.requests.filter(r=>`${r.pcvNumber} ${r.purpose} ${r.requesterName||''}`.toLowerCase().includes(query.toLowerCase()))};
  const rows=buildPettyCashVoucherRows(filtered,verifiedOnly);
  const title=`${verifiedOnly?'Summary of Petty Cash Expenses':'Petty Cash Voucher Register · includes unverified packages'} · FY ${data.summary?.fiscalYear}`;
  return <section className="rounded-xl border border-border bg-card p-4"><div className="flex flex-wrap justify-between gap-3"><h3 className="text-[14px] font-semibold">Petty Cash Vouchers</h3><div className="flex gap-2"><button onClick={()=>downloadBudgetCsv('petty-cash-vouchers.csv',PCV_HEADINGS,rows)} className="rounded-lg border px-3 py-2 text-[12px]">CSV</button><button onClick={()=>printBudgetTable(title,PCV_HEADINGS,rows)} className="rounded-lg border px-3 py-2 text-[12px]">Print / PDF</button></div></div><p className="mt-2 text-[12px] text-muted-foreground">A PCV keeps its number through releases and correction versions. Uploaded receipts are not verified expenses until Accounting settles them.</p><div className="mt-3 flex flex-wrap gap-3"><input aria-label="Find voucher" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find PCV, purpose or recipient" className="h-10 rounded-lg border px-3 text-[12px]"/><label className="flex items-center gap-2 text-[12px]"><input type="checkbox" checked={verifiedOnly} onChange={e=>setVerifiedOnly(e.target.checked)}/>Verified expenses only</label></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[1100px] text-[12px]"><thead><tr>{PCV_HEADINGS.map(h=><th key={h} className="border p-2 text-left">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className={row[0]?'bg-muted font-medium':''}>{row.map((c,j)=><td key={j} className={`border p-2 ${j===6||j===7?'text-right tabular-nums':''}`}>{typeof c==='number'?peso.format(c):c}</td>)}</tr>)}</tbody></table></div>{!rows.length&&<p className="mt-4 text-[12px] text-muted-foreground">No {verifiedOnly?'settled expenses':'authorized vouchers'} in this selection.</p>}</section>;
}
