import { useState,type DragEvent } from 'react';
import { ChevronRight,ChevronDown,MoreHorizontal,Plus } from 'lucide-react';
import { ActionMenu,InlineEditableText,WorkspacePopover } from '../../../components/ui/workspace';
import type { Task } from '../../tasks';
import type { Subtask } from '../../subtasks';
import type { Organization,UserProfile } from '../../../types';
import type { ProjectColumn,ProjectGroup } from '../types';
import { PROJECT_COLUMNS } from '../types';
import { groupSummary,canEditProjectTask,type TableSort } from '../selectors';
import { updateProjectGroup,deleteProjectGroup,createWorkspaceTask,reorderWorkspaceTasks } from '../services/workspaceService';
import { ProjectTaskRow } from './ProjectTaskRow';
export function ProjectGroupTable({group,groups,tasks,allTasks,subtasks,columns,profiles,orgs,canManage,canStaff=false,officeId,userId,projectId,onOpen,onOpenSubitem,refreshSubitems,refreshGroups,onHideColumn,onSort,reorderable,run}:{group:ProjectGroup;groups:ProjectGroup[];tasks:Task[];allTasks:Task[];subtasks:Subtask[];columns:ProjectColumn[];profiles:UserProfile[];orgs:Organization[];canManage:boolean;canStaff?:boolean;officeId:string;userId:string;projectId:string;onOpen:(id:string)=>void;onOpenSubitem:(s:Subtask)=>void;refreshSubitems:()=>Promise<void>;refreshGroups:()=>Promise<void>;onHideColumn:(c:ProjectColumn)=>void;onSort:(s:TableSort)=>void;reorderable:boolean;run:(f:()=>Promise<void>)=>Promise<void>}){
 const [collapsed,setCollapsed]=useState(false),[title,setTitle]=useState(''),[busy,setBusy]=useState(false);const summary=groupSummary(tasks);
 const saveGroup=async(changes:Parameters<typeof updateProjectGroup>[1])=>{await updateProjectGroup(group.id,changes);await refreshGroups();};
 const move=async(taskId:string,beforeId?:string)=>{const ordered=tasks.map(t=>t.id).filter(id=>id!==taskId);const index=beforeId?ordered.indexOf(beforeId):ordered.length;ordered.splice(Math.max(0,index),0,taskId);await reorderWorkspaceTasks(projectId,group.id,ordered);};
 const drop=(e:DragEvent,beforeId?:string)=>{e.preventDefault();if(!reorderable)return;const id=e.dataTransfer.getData('application/eflow-task');if(!tasks.some(t=>t.id===id))return;void run(()=>move(id,beforeId));};
 return <section className="pt-group" style={{'--group-color':group.color} as React.CSSProperties} data-tour-id="project-task-group">
  <header><button type="button" aria-expanded={!collapsed} aria-label={(collapsed?'Expand ':'Collapse ')+group.title} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<ChevronRight size={20}/>:<ChevronDown size={20}/>}</button><InlineEditableText label={'group '+group.title} value={group.title} maxLength={120} disabled={!canManage} onSave={title=>saveGroup({title})}/><span>{summary.count} task{summary.count===1?'':'s'}</span>
   {canManage&&<WorkspacePopover trigger={<button type="button" className="pt-color" aria-label={'Color for '+group.title} style={{background:group.color}}/>}><div className="pt-colors">{['#087f8c','#579bfc','#00b97d','#8b6be8','#df526d','#f4ae36'].map(color=><button type="button" key={color} style={{background:color}} aria-label={'Set group color '+color} onClick={()=>{void run(()=>saveGroup({color}));}}/>)}</div></WorkspacePopover>}
   <ActionMenu trigger={<button type="button" aria-label={'Group actions for '+group.title}><MoreHorizontal size={17}/></button>} actions={[{id:'collapse',label:collapsed?'Expand group':'Collapse group',onSelect:()=>setCollapsed(!collapsed)},{id:'delete',label:'Delete empty group',disabled:!canManage||group.isDefault||allTasks.some(t=>t.groupId===group.id),onSelect:()=>{void run(async()=>{await deleteProjectGroup(group.id);await refreshGroups();});}}]}/>
  </header>
  {collapsed?<div className="pt-collapsed"><span>{summary.completed}/{summary.count} completed</span><div className="pt-status-summary">{tasks.map(t=><i key={t.id} style={{background:({'completed':'#00b97d','for_review':'#8b6be8','in_progress':'#f4ae36'} as Record<string,string>)[t.status]||'#579bfc'}}/>)}</div><span>{summary.effort}h effort</span><span>₱{summary.budget.toLocaleString()} estimated</span></div>:<div className="pt-table-scroll"><table aria-label={group.title+' tasks'}><thead><tr><th className="pt-drag-col"/><th className="pt-title-col" scope="col">Task</th>{columns.map(c=><th key={c} scope="col"><span>{PROJECT_COLUMNS.find(x=>x.id===c)?.label}<ActionMenu trigger={<button className="pt-column-menu" type="button" aria-label={'Column actions for '+PROJECT_COLUMNS.find(x=>x.id===c)?.label}><MoreHorizontal size={13}/></button>} actions={[{id:'hide',label:'Hide column',onSelect:()=>onHideColumn(c)},...(['priority','timeline'].includes(c)?[{id:'sort',label:'Sort by '+(c==='timeline'?'due date':'priority'),onSelect:()=>onSort(c==='timeline'?'deadline':'priority')}]:[])]}/></span></th>)}<th className="pt-actions-col"/></tr></thead><tbody>
   {tasks.map((task,index)=><ProjectTaskRow key={task.id} task={task} tasks={allTasks} groups={groups} profiles={profiles} orgs={orgs} columns={columns} canSetOffice={canManage} editable={canEditProjectTask(task,canManage||canStaff,officeId)} userId={userId} subtasks={subtasks.filter(s=>s.taskId===task.id)} onOpen={()=>onOpen(task.id)} onOpenSubitem={onOpenSubitem} refreshSubitems={refreshSubitems} reorderable={reorderable} run={run} onDrag={e=>e.dataTransfer.setData('application/eflow-task',task.id)} onDrop={e=>drop(e,task.id)} onMove={offset=>{const target=tasks[index+offset];if(!target)return;void run(()=>move(task.id,offset<0?target.id:tasks[index+2]?.id));}}/>)}
   {!tasks.length&&<tr><td colSpan={columns.length+3} className="pt-empty-group">No tasks in this group.</td></tr>}
   {canManage&&<tr className="pt-add-row" onDragOver={e=>{if(reorderable)e.preventDefault();}} onDrop={e=>drop(e)}><td/><td colSpan={columns.length+2}><form onSubmit={e=>{e.preventDefault();if(!title.trim()||busy)return;setBusy(true);void run(async()=>{await createWorkspaceTask(projectId,group.id,title);setTitle('');}).finally(()=>setBusy(false));}}><Plus size={15}/><input aria-label={'Add task to '+group.title} placeholder="Add task" value={title} maxLength={300} disabled={busy} onChange={e=>setTitle(e.target.value)}/><button disabled={!title.trim()||busy}>{busy?'Adding…':'Add'}</button></form></td></tr>}
  </tbody><tfoot><tr><td/><td>{summary.count} tasks · {summary.progress}% complete</td>{columns.map(c=><td key={c}>{c==='effort'?summary.effort+'h':c==='budget'?'₱'+summary.budget.toLocaleString():c==='progress'?summary.completed+' completed':''}</td>)}<td/></tr></tfoot></table></div>}
 </section>;
}
