"""Phase 7 acceptance against the named main database; every test record rolls back."""
import argparse, json
from pathlib import Path
from dotenv import dotenv_values
from urllib.parse import urlparse, unquote
import psycopg2
p=argparse.ArgumentParser();p.add_argument('--project-ref',required=True);p.add_argument('--preflight',action='store_true');p.add_argument('--rollback-rehearsal',action='store_true');args=p.parse_args()
dsn=dotenv_values('.env')['EFLOW_DATABASE_URL'];assert unquote(urlparse(dsn).username)=='postgres.'+args.project_ref,'Explicit database target mismatch'
conn=psycopg2.connect(dsn,sslmode='require',connect_timeout=15);c=conn.cursor();checks=[]
def q(sql,params=None):
 c.execute(sql,params);return c.fetchone()[0] if c.description else None
def ok(label,value):
 assert value,label;checks.append(label);print('Passed: '+label,flush=True)
def denied(label,sql,params=None):
 c.execute('savepoint denied')
 try:c.execute(sql,params)
 except psycopg2.Error:c.execute('rollback to savepoint denied');ok(label,True)
 else:raise AssertionError(label+' unexpectedly allowed')
 finally:c.execute('release savepoint denied')
def identity(uid=None):
 c.execute('reset role');q("select set_config('request.jwt.claim.sub',%s,true)",(uid or '',))
 if uid:c.execute('set local role authenticated')
def ready(project):return q('select phase7_project_readiness(%s)',(project,))
def review(project):
 for kind in ('structure','dates','budget'):q('select phase7_review_project(%s,%s)',(project,kind))
try:
 if args.preflight:
  sql=next(Path('supabase/migrations').glob('*phase7_readiness_governance.sql')).read_text(encoding='utf-8');c.execute(sql.replace('begin;\n','',1).removesuffix('commit;\n').removesuffix('commit;'))
 c.execute("select p.id,p.org_id from profiles p join organizations o on o.head_user_id=p.id where p.role='head' and p.is_active and exists(select 1 from profiles m where m.role='member' and m.org_id=p.org_id and m.is_active) limit 1");head,office=map(str,c.fetchone())
 member=str(q("select id from profiles where role='member' and org_id=%s and is_active limit 1",(office,)))
 admin=str(q("select id from profiles where role='admin' and is_active limit 1"))
 accounting=str(q("select id from profiles where role='accounting_staff' and is_active limit 1"))
 other=str(q("select id from profiles where role='head' and org_id<>%s and is_active limit 1",(office,)))
 identity(head)
 denied('New active projects cannot bypass planning','select create_project_with_details(%s::jsonb)',(json.dumps({'title':'Invalid activation','org_id':office,'status':'active'}),))
 project=str(q('select (create_project_with_details(%s::jsonb)).id',(json.dumps({'title':'Phase 7 rollback verification','org_id':office,'start_date':'2026-10-05','target_date':'2026-10-25'}),)))
 group=str(q('select id from project_groups where project_id=%s and is_default',(project,)))
 task=str(q("select (phase3_create_task(%s,%s,'Complete delivery')).id",(project,group)))
 ok('New plan exposes missing reviews and owners',not ready(project)['ready'])
 denied('Direct active status requires readiness',"update projects set status='active' where id=%s",(project,))
 review(project)
 ok('Confirmed reviews do not hide missing owners',not ready(project)['ready'])
 q('select assign_task(%s,%s,%s)',(task,member,'Member'))
 ok('Assigned eligible owner completes readiness',ready(project)['canActivate'])
 identity();other_office=str(q('select org_id from profiles where id=%s',(other,)))
 participation=str(q("insert into project_offices(project_id,office_id,relationship_type,invitation_status) values(%s,%s,'observer','pending') returning id",(project,other_office)))
 identity(head)
 ok('Pending Office invitation blocks readiness',not next(x for x in ready(project)['checks'] if x['key']=='invitations')['ok'])
 denied('Pending Office participation blocks activation','select phase7_activate_project(%s)',(project,))
 identity();q('delete from project_offices where id=%s',(participation,));identity(head);review(project)
 for uid,role in [(member,'Member'),(admin,'Admin'),(accounting,'Accounting'),(other,'Other Head')]:
  identity(uid)
  denied(role+' cannot review Lead readiness','select phase7_review_project(%s,\'budget\')',(project,))
  denied(role+' cannot activate Lead project','select phase7_activate_project(%s)',(project,))
 identity(head)
 denied('Metadata changes cannot piggyback on activation',"update projects set status='active',description='Unreviewed scope' where id=%s",(project,))
 q('select phase7_activate_project(%s)',(project,))
 ok('Head activation passes all checks',q("select status='active' from projects where id=%s",(project,)))
 q('select phase3_patch_task(%s,%s::jsonb)',(task,json.dumps({'title':'Minor title correction','priority':'high'})))
 ok('Minor title and priority edits retain active state',q("select status='active' from projects where id=%s",(project,)) and ready(project)['ready'])
 q('select phase3_patch_task(%s,%s::jsonb)',(task,json.dumps({'budget_impact':500})))
 ok('Material budget change pauses active project',q("select status='on_hold' from projects where id=%s",(project,)))
 ok('Only budget review becomes stale',[(x['key'],x['ok']) for x in ready(project)['checks'][:3]]==[('structure',True),('dates',True),('budget',False)])
 denied('Stale reviews block reactivation','select phase7_activate_project(%s)',(project,))
 q('select phase7_review_project(%s,\'budget\')',(project,));q('select phase7_activate_project(%s)',(project,))
 q("update projects set target_date='2026-10-26' where id=%s",(project,))
 ok('Project schedule change requires date review',q("select status='on_hold' from projects where id=%s",(project,)) and not next(x for x in ready(project)['checks'] if x['key']=='dates')['ok'])
 review(project);q('select phase7_activate_project(%s)',(project,))
 identity(member)
 ok('Member can read project readiness without review authority',ready(project)['ready'])
 q('select transition_task_status(%s,\'in_progress\')',(task,))
 ok('Work progress does not invalidate reviews',ready(project)['ready'])
 identity(head)
 denied('Open work still blocks closeout','select complete_project(%s,%s)',(project,'Premature closeout'))
 identity();q("select set_config('eflow.allow_status_write','on',true)");q("update tasks set status='completed',percent_complete=100 where id=%s",(task,));q("select set_config('eflow.allow_status_write','off',true)")
 identity(head)
 ok('Completed status without an approved submission blocks closure',any(b['status']=='evidence_required' for b in q('select get_project_completion_readiness(%s)',(project,))['blockers']))
 identity();q("select set_config('eflow.allow_status_write','on',true)");q("update tasks set status='in_progress',percent_complete=90 where id=%s",(task,));q("select set_config('eflow.allow_status_write','off',true)")
 identity(member);q('select submit_task_for_review(%s,%s::jsonb)',(task,json.dumps({'note':'Completed assessment and delivery evidence.'})))
 ok('Member submits completion evidence through the canonical RPC',q("select status='for_review' from tasks where id=%s",(task,)))
 denied('Member cannot self-approve completion','select transition_task_status(%s,\'completed\')',(task,))
 identity(head);q('select decide_task_review(%s,true,\'Evidence reviewed and accepted\',null)',(task,))
 ok('Head finalizes the Member submission',q("select exists(select 1 from task_submissions where task_id=%s and status='approved')",(task,)))
 identity(head)
 ok('Approved evidence permits closeout when work and finances are clear',q('select get_project_completion_readiness(%s)',(project,))['canComplete'])
 summary=q('select phase7_closeout_summary(%s)',(project,));ok('Summary includes work, evidence, Offices, estimates and contributors',summary['tasks']==1 and summary['completed']==1 and summary['evidence']==1 and summary['offices']==1 and summary['budgetEstimate']==500 and summary['contributors']>=1)
 q('select complete_project(%s,%s)',(project,'Delivery and handover confirmed'))
 ok('Head closes the project through existing audited workflow',q("select status='completed' from projects where id=%s",(project,)))
 q('select archive_completed_project(%s,%s)',(project,'Handover complete'))
 ok('Completed project archives successfully',q("select status='archived' from projects where id=%s",(project,)))
 q("update projects set status='active',archived_at=null where id=%s",(project,))
 ok('Existing archive restore resumes a currently reviewed plan',q("select status='active' from projects where id=%s",(project,)))
 q('select complete_project(%s,%s)',(project,'Restored delivery verified'));q('select archive_completed_project(%s,%s)',(project,'Rehearsal archive'))
 identity();q('delete from project_readiness_reviews where project_id=%s',(project,));identity(head)
 q("update projects set status='active',archived_at=null where id=%s",(project,))
 ok('Legacy archive restoration remains available and returns to Planning for review',q("select status='planning' from projects where id=%s",(project,)))
 review(project);q('select phase7_activate_project(%s)',(project,))
 ok('Restored legacy plan activates after fresh reviews',q("select status='active' from projects where id=%s",(project,)))
 identity()
 ok('Material change and readiness reviews leave audit records',q("select count(*)>=2 from audit_events where entity_id=%s and action in ('project.material_change_review','project.readiness_review')",(project,)))
 ok('Internal helper functions are not callable by authenticated users',not q("select has_function_privilege('authenticated','eflow_phase7.readiness(uuid)','execute')"))
 identity();c.execute('set local role anon');denied('Anonymous cannot read readiness','select phase7_project_readiness(%s)',(project,));identity()
 if args.rollback_rehearsal:
  before=q("select pg_get_functiondef('public.project_completion_readiness_internal(uuid)'::regprocedure)")
  c.execute('savepoint rollback_rehearsal')
  c.execute(Path('scripts/phase7-rollback.sql').read_text(encoding='utf-8'))
  ok('Rollback restores prior closeout implementation',q("select pg_get_functiondef('public.project_completion_readiness_internal(uuid)'::regprocedure) not like '%eflow_phase7.baseline_completion%'"))
  ok('Rollback retains Phase 6 Office authority',bool(q("select to_regprocedure('public.phase6_responsible_office(uuid,uuid)')")))
  c.execute('rollback to savepoint rollback_rehearsal')
  ok('Rollback rehearsal restores Phase 7 after transaction rollback',q("select pg_get_functiondef('public.project_completion_readiness_internal(uuid)'::regprocedure)")==before)
 print(str(len(checks))+' Phase 7 database checks passed; all verification records rolled back.',flush=True)
finally:
 conn.rollback();conn.close()
