import argparse,json,sys
from pathlib import Path
from dotenv import dotenv_values
from urllib.parse import urlparse,unquote
import psycopg2
parser=argparse.ArgumentParser(description='Rollback-only Phase 3 checks against the explicitly selected database.');parser.add_argument('--project-ref',required=True);args=parser.parse_args()
root=Path.cwd();conf=dotenv_values(root/'.env');url=conf['EFLOW_DATABASE_URL'];assert unquote(urlparse(url).username)=='postgres.'+args.project_ref,'Database target does not match --project-ref'
conn=psycopg2.connect(url,sslmode='require');c=conn.cursor();checks=[]
def q(sql,args=None):
 c.execute(sql,args);return c.fetchone()[0] if c.description else None
def ok(label,value):
 assert value,label;checks.append(label);print('Passed: '+label,flush=True)
def denied(label,sql,args=None):
 c.execute('savepoint deny')
 try:c.execute(sql,args)
 except psycopg2.Error:c.execute('rollback to savepoint deny');checks.append(label);print('Passed: '+label,flush=True)
 else:raise AssertionError(label+' unexpectedly allowed')
 finally:c.execute('release savepoint deny')
def identity(uid=None):
 c.execute('reset role');q("select set_config('request.jwt.claim.sub',%s,true)",(uid or '',))
 if uid:c.execute('set local role authenticated')
try:
 c.execute("select p.id,p.org_id from profiles p join organizations o on o.head_user_id=p.id where p.role='head' and p.is_active and exists(select 1 from profiles m where m.role='member' and m.org_id=p.org_id and m.is_active) limit 1");head,office=map(str,c.fetchone())
 member=str(q("select id from profiles where role='member' and org_id=%s and is_active limit 1",(office,)))
 other=str(q("select id from profiles where role='head' and org_id<>%s and is_active limit 1",(office,)))
 admin=str(q("select id from profiles where role='admin' and is_active limit 1"))
 identity(head);project=str(q("select (create_project_with_details(%s::jsonb)).id",(json.dumps({'title':'Phase 3 rollback-only verification','org_id':office}),)))
 group=str(q('select id from project_groups where project_id=%s and is_default',(project,)))
 ok('Project receives a default group atomically',bool(group))
 second=str(q("insert into project_groups(project_id,title,position) values(%s,'Implementation',1) returning id",(project,)))
 a=str(q("select (phase3_create_task(%s,%s,'Prepare assessment')).id",(project,group)))
 b=str(q("select (phase3_create_task(%s,%s,'Review findings')).id",(project,group)))
 ok('Tasks use existing records and canonical project links',q('select linked_project_id=%s and group_id=%s and status=\'pending_assignment\' from tasks where id=%s',(project,group,a)))
 q('select phase3_patch_task(%s,%s::jsonb)',(a,json.dumps({'title':'Updated assessment','priority':'high','estimated_hours':8,'budget_impact':1500,'start_date':'2026-10-05','deadline':'2026-10-09'})))
 ok('Inline planning fields persist together',q("select title='Updated assessment' and priority='high' and estimated_hours=8 and budget_impact=1500 and deadline=due_date from tasks where id=%s",(a,)))
 q('select phase3_patch_task(%s,%s::jsonb)',(b,json.dumps({'dependency_ids':[a]})))
 denied('Dependency cycles rejected','select phase3_patch_task(%s,%s::jsonb)',(a,json.dumps({'dependency_ids':[b]})))
 denied('Self dependency rejected','select phase3_patch_task(%s,%s::jsonb)',(a,json.dumps({'dependency_ids':[a]})))
 denied('Lifecycle status cannot be patched','select phase3_patch_task(%s,%s::jsonb)',(a,json.dumps({'status':'completed'})))
 denied('Office cannot be reassigned through table patch','select phase3_patch_task(%s,%s::jsonb)',(a,json.dumps({'org_id':office})))
 denied('Invalid dates rollback entire edit','select phase3_patch_task(%s,%s::jsonb)',(a,json.dumps({'title':'Must roll back','start_date':'2026-11-05'})))
 ok('Failed date edit retained original title',q("select title='Updated assessment' from tasks where id=%s",(a,)))
 denied('Negative effort rejected','select phase3_patch_task(%s,%s::jsonb)',(a,json.dumps({'estimated_hours':-1})))
 q('select phase3_reorder_tasks(%s,%s,%s::uuid[])',(project,group,[b,a]))
 ok('Complete task order saves atomically',q('select workspace_position=0 from tasks where id=%s',(b,)))
 denied('Incomplete reorder rejected','select phase3_reorder_tasks(%s,%s,%s::uuid[])',(project,group,[a]))
 q('select phase3_patch_task(%s,%s::jsonb)',(b,json.dumps({'group_id':second,'workspace_position':0})))
 denied('Non-empty group deletion blocked','delete from project_groups where id=%s',(second,))
 denied('Group project identity immutable','update project_groups set is_default=true where id=%s',(second,))
 project2=str(q("select (create_project_with_details(%s::jsonb)).id",(json.dumps({'title':'Other project','org_id':office}),)))
 foreign=str(q('select id from project_groups where project_id=%s',(project2,)))
 denied('Cross-project group rejected','select phase3_patch_task(%s,%s::jsonb)',(a,json.dumps({'group_id':foreign})))
 denied('Cross-project dependency rejected','select phase3_patch_task(%s,%s::jsonb)',(a,json.dumps({'dependency_ids':[str(q("select (phase3_create_task(%s,%s,'Foreign task')).id",(project2,foreign)))]})))
 identity(other)
 ok('Other Office cannot see groups',q('select count(*)=0 from project_groups where project_id=%s',(project,)))
 denied('Other Head cannot patch project task','select phase3_patch_task(%s,%s::jsonb)',(a,'{"title":"Unauthorized"}'))
 identity(member)
 denied('Member cannot create project task','select phase3_create_task(%s,%s,%s)',(project,group,'Unauthorized'))
 denied('Member cannot patch planning fields','select phase3_patch_task(%s,%s::jsonb)',(a,'{"priority":"low"}'))
 identity(admin)
 ok('Admin has no operational group access',q('select count(*)=0 from project_groups where project_id=%s',(project,)))
 denied('Admin cannot create project task','select phase3_create_task(%s,%s,%s)',(project,group,'Unauthorized'))
 identity(head)
 q('select assign_task(%s,%s)',(a,head))
 sid=str(q("insert into subtasks(task_id,title,created_by,source) values(%s,'Prepare supporting evidence',%s,'manual') returning id",(a,head)))
 ok('Subitems retain existing task relationship and review lifecycle',q("select task_id=%s and status='todo' from subtasks where id=%s",(a,sid)))
 q('select transition_task_status(%s,\'in_progress\')',(a,))
 ok('Starting work uses existing audited lifecycle',q("select status='in_progress' from tasks where id=%s",(a,)))
 denied('Evidence requirement still blocks review','select transition_task_status(%s,\'for_review\')',(a,))
 denied('Existing closeout blockers are preserved',"update projects set status='completed' where id=%s",(project2,))
 empty=str(q("select (create_project_with_details(%s::jsonb)).id",(json.dumps({'title':'Empty completion check','org_id':office}),)))
 empty_group=str(q('select id from project_groups where project_id=%s',(empty,)))
 denied('Unfinished project cannot be archived',"update projects set status='archived' where id=%s",(empty,))
 q('delete from projects where id=%s',(empty,))
 ok('Project deletion cascades empty groups',q('select count(*)=0 from project_groups where id=%s',(empty_group,)))
 identity();c.execute('set local role anon')
 denied('Anonymous cannot execute workspace mutation','select phase3_create_task(%s,%s,%s)',(project,group,'Unauthorized'))
 identity()
 ok('Group mutations produce audit events',q("select exists(select 1 from audit_events where entity_id=%s and action='project.group.insert')",(project,)))
 print(str(len(checks))+' database checks passed; all verification records rolled back.',flush=True)
finally:conn.rollback();conn.close()
