import {useEffect,useRef,useState} from 'react';
import {fetchAccess,RemovalDialog,ProjectAccessPanel,type AccessSnapshot,ACCESS_CHANGED_EVENT} from '../../project-access';
import {ProjectInvitations} from '../../project-invitations';
import {useAuth} from '../../../contexts/AuthContext';
import {FeatureDialog} from '../../../components/ui/FeatureDialog';
import {requestNavigation} from '../../../shared/navigationGuard';
import {OfficeMembersEditor,useProjectOfficeContext} from '../../project-offices';
import type {Task} from '../../tasks';
import type {UserProfile} from '../../../types';
import {fetchMembers} from '../services/memberService';
import type {MemberOffice,MembersSnapshot,SelectedMember} from '../types';
import {MemberTermsEditor} from './MemberTermsEditor';
import '../projectMembers.css';
export function ProjectMembers(props:{projectId:string;projectStatus:string;profiles:UserProfile[];tasks:Task[];onOpenTask:(id:string)=>void}){const {user}=useAuth();return <MembersContent key={`${user?.id}:${props.projectId}`} {...props}/>;}
function MembersContent({projectId,projectStatus,profiles,tasks,onOpenTask}:{projectId:string;projectStatus:string;profiles:UserProfile[];tasks:Task[];onOpenTask:(id:string)=>void}){
 const {user}=useAuth(),officeState=useProjectOfficeContext();const [data,setData]=useState<MembersSnapshot>(),[error,setError]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[office,setOffice]=useState<MemberOffice>(),[terms,setTerms]=useState<SelectedMember>();const [access,setAccess]=useState<AccessSnapshot>(),[removing,setRemoving]=useState<SelectedMember>();
 const active=useRef(true),generation=useRef(0),hold=useRef(false);hold.current=!!office||!!terms||!!removing;
 async function reload(){const run=++generation.current;setData(undefined);setError('');setLoading(true);try{const next=await fetchMembers(projectId);const permissions=await fetchAccess(projectId).catch(()=>undefined);if(active.current&&run===generation.current){setData(next);setAccess(permissions);}}catch(reason){if(active.current&&run===generation.current)setError((reason as Error).message);}finally{if(active.current&&run===generation.current)setLoading(false);}}
 useEffect(()=>{active.current=true;void reload();const refresh=()=>{if(!hold.current)void reload();};window.addEventListener('focus',refresh);window.addEventListener(ACCESS_CHANGED_EVENT,refresh);const timer=window.setInterval(refresh,15000);return()=>{active.current=false;++generation.current;window.removeEventListener('focus',refresh);window.removeEventListener(ACCESS_CHANGED_EVENT,refresh);clearInterval(timer);};},[projectId]);
 const closed=['completed','archived'].includes(projectStatus);
 const visible=data?.members.filter(member=>`${member.name} ${member.office_name||''} ${member.engagement}`.toLowerCase().includes(query.trim().toLowerCase()))||[];
 return <section className="r7-members" aria-label="Project Members"><h2>Members</h2><p>Selected people for this project. Office membership is shared with Offices; access never changes an account role or Office affiliation.</p>
 <label className="r7-member-search">Search project members<input type="search" placeholder="Name, Office or engagement" value={query} onChange={e=>setQuery(e.target.value)}/></label>
 {loading&&<p role="status">Loading project members…</p>}{error&&<p role="alert">{error}<button type="button" onClick={()=>void reload()}>Retry Members</button></p>}
 {data?.offices.map(item=><div key={item.id} className="r7-node"><h3>{item.name}</h3><p>{data.members.filter(member=>member.office===item.office_id).length} selected · {item.relationship_type} · {item.invitation_status}</p>
 {!closed&&item.can_select&&item.invitation_status==='joined'&&item.relationship_type!=='observer'&&<button type="button" onClick={()=>setOffice(item)}>Add existing members · {item.name}</button>}
 {item.eligible_count===0&&<p>No onboarded eligible staff in this Office. Use Invitations below to request Head-approved project membership. No owner is assigned automatically.</p>}</div>)}
 <ProjectInvitations project={projectId}/><ProjectAccessPanel project={projectId} onChange={reload}/>
 <div className="pt-subitems-table-scroll"><table aria-label="Selected project members"><thead><tr>{['Person','Office','Engagement','Effective access','Responsibilities','Permitted actions'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>
 {visible.map(member=><tr key={`${member.office}:${member.user_id}`}><td>{member.name}</td><td>{member.office_name||'Personal project'}</td><td>{member.engagement}{member.access_end&&<small> · Until {new Date(member.access_end).toISOString()}</small>}{member.until_close&&<small> · Until project closes</small>}</td><td>{(member.can_read??member.eligible)?member.access||'member':member.access_ended_at?'Ended':'Inactive / expired / unavailable'}</td><td>{member.responsibilities?.length?member.responsibilities.map(role=><button key={`${role.root}:${role.node||''}:${role.role}`} type="button" onClick={()=>onOpenTask(role.root)}>{role.title} · {role.role}</button>):'No assigned responsibility'}</td><td>{member.eligible?'View authorized project work; execute assigned work; delegate only an appointed branch':member.can_read?'View authorized project information; no execution or delegation':'Historical membership; current execution unavailable'}{!['guest','share'].includes(member.state)&&!closed&&(data?.kind==='personal'&&data.can_select||data?.offices.some(item=>item.office_id===member.office&&item.can_select))&&<button type="button" onClick={()=>setTerms(member)}>Edit access terms for {member.name}</button>}{access&&(access.can_remove_personal||access.can_remove_offices.includes(member.office||''))&&<button type="button" onClick={()=>setRemoving(member)}>Review removal · {member.name}</button>}{member.state==='guest'&&!member.eligible&&<small>Fresh Head-approved invitation required to renew guest access.</small>}</td></tr>)}
 </tbody></table></div>{data&&!visible.length&&<p>{query?'No project members match.':'No selected members yet. The appointed Office Head chooses existing people for this project.'}</p>}
 {office&&<FeatureDialog title={`Select project members · ${office.name}`} onClose={()=>void requestNavigation(()=>setOffice(undefined))}><OfficeMembersEditor office={office} profiles={profiles} members={data?.members.filter(m=>m.project_office_id&&!m.access_ended_at&&(!m.access_end||new Date(m.access_end).getTime()>Date.now())).map(m=>({project_office_id:m.project_office_id!,user_id:m.user_id}))||[]} tasks={tasks} actorId={user?.id||''} disabledReason={closed?'Closed projects are read-only.':''} onOpenTask={onOpenTask} onCancel={()=>setOffice(undefined)} onSaved={async()=>{await officeState?.refresh();await reload();}}/></FeatureDialog>}
 {removing&&<RemovalDialog project={projectId} user={removing.user_id} office={data?.kind==='personal'?null:removing.office} name={removing.name} onClose={()=>setRemoving(undefined)} onRemoved={async()=>{await officeState?.refresh();await reload();}}/>}
 {terms&&<FeatureDialog title="Project access terms" onClose={()=>void requestNavigation(()=>setTerms(undefined))}><MemberTermsEditor timezone={data?.timezone||'Asia/Singapore'} project={projectId} member={terms} onClose={()=>{setTerms(undefined);void reload();}} onSaved={async()=>{await officeState?.refresh();}}/></FeatureDialog>}
 </section>;
}
