// @vitest-environment jsdom
import { act, cleanup, renderHook, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { ProjectImportDraft } from '../../src/app/features/project-import/types';
const calls=vi.hoisted(()=>({generate:vi.fn(),save:vi.fn(),read:vi.fn()}));
vi.mock('../../src/app/features/project-import/services/projectImportService',()=>({generateProjectDraft:calls.generate,importReviewedProject:calls.save,importReviewedProjectWithOffices:calls.save,ProjectImportSaveError:class extends Error{retrySameBatch=true}}));
vi.mock('../../src/app/features/project-import/services/documentService',()=>({readProjectDocument:calls.read}));
import { useProjectImport } from '../../src/app/features/project-import/hooks/useProjectImport';
import { projectImportSummary } from '../../src/app/features/project-import/selectors/reviewSummary';
const draft:ProjectImportDraft={schemaVersion:1,project:{title:'Source',description:'',objectives:'',startDate:'',targetDate:''},offices:[],warnings:[],groups:[{key:'g',title:'Work',color:'#579bfc',existingGroupId:'',tasks:[{key:'t',title:'Assess',description:'',priority:'medium',estimatedHours:8,startDate:'',dueDate:'',officeKey:'',dependencies:[],subitems:[{title:'Collect',dueDate:''}],sourceQuote:'',included:true}]}]};
beforeEach(()=>{vi.clearAllMocks();calls.generate.mockResolvedValue(draft);calls.save.mockResolvedValue({taskCount:1,subitemCount:1,groupCount:1});});afterEach(cleanup);
describe('Phase 15 import concurrency and receipts',()=>{
 it('counts included work without making proposed Offices operational',()=>{expect(projectImportSummary({...draft,offices:[{key:'o',name:'Proposed',evidence:'Source',officeId:'',confirmed:false}]})).toMatchObject({tasks:1,groups:1,subitems:1,proposedOffices:['Proposed'],unconfirmedOffices:1});});
 it('deduplicates generation before React renders and ignores a departed context',async()=>{let finish!:(draft:ProjectImportDraft)=>void;calls.generate.mockImplementation(()=>new Promise(r=>{finish=r;}));const view=renderHook(()=>useProjectImport('p',vi.fn()));let first!:Promise<void>;act(()=>{first=view.result.current.generate();void view.result.current.generate();});expect(calls.generate).toHaveBeenCalledOnce();view.unmount();await act(async()=>{finish(draft);await first;});});
 it('locks the same batch and reviewed values on ambiguous save, then receipts a committed result even if refresh throws',async()=>{calls.save.mockRejectedValueOnce(new Error('Unknown outcome'));const refreshed=vi.fn(()=>{throw new Error('Refresh failed');});const view=renderHook(()=>useProjectImport('p',refreshed));await act(async()=>view.result.current.generate());await act(async()=>view.result.current.save());expect(view.result.current.retryPending).toBe(true);const first=calls.save.mock.calls[0];await act(async()=>{await view.result.current.save();await view.result.current.save();});expect(calls.save).toHaveBeenCalledTimes(2);expect(calls.save.mock.calls[1].slice(1)).toEqual(first.slice(1));expect(view.result.current.result?.taskCount).toBe(1);expect(view.result.current.error).toContain('Work was added');});
 it('deduplicates the same save while its RPC is pending',async()=>{let done!:()=>void;calls.save.mockImplementation(()=>new Promise(r=>{done=()=>r({taskCount:1});}));const view=renderHook(()=>useProjectImport('p',vi.fn()));await act(async()=>view.result.current.generate());let operation!:Promise<void>;act(()=>{operation=view.result.current.save();void view.result.current.save();});await waitFor(()=>expect(calls.save).toHaveBeenCalledOnce());await act(async()=>{done();await operation;});});
});
