// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
const calls=vi.hoisted(()=>({read:vi.fn(),private:vi.fn(),update:vi.fn(),confirm:vi.fn(),review:vi.fn(),draft:vi.fn(),upload:vi.fn()}));
vi.mock('../../src/app/contexts/AuthContext',()=>({useAuth:()=>({user:{id:'me'}})}));
vi.mock('../../src/app/components/ui/useConfirmation',()=>({useConfirmation:()=>({confirm:calls.review,dialog:null})}));
vi.mock('../../src/app/features/professional-profile/services/professionalProfileService',()=>({getProfessionalProfile:calls.read,getMyPds:calls.private,updateProfessionalProfile:calls.update,confirmProfessionalProfile:calls.confirm,getPdsDraft:calls.draft,uploadPds:calls.upload}));
import { ProfessionalProfilePanel } from '../../src/app/features/professional-profile/components/ProfessionalProfilePanel';
const values={skills:['Planning'],education:[],trainings:[],certifications:[],work_experience:[],specializations:[],competency_summary:'Work summary'};
const profile={...values,user_id:'me',confirmed_by_user:false};
beforeEach(()=>{vi.clearAllMocks();calls.read.mockResolvedValue({profile});calls.private.mockResolvedValue({documents:[]});calls.review.mockResolvedValue(true);calls.confirm.mockResolvedValue({profile:{...profile,confirmed_by_user:true}});calls.update.mockResolvedValue({profile});});afterEach(cleanup);
describe('Phase 15 owner review and confirmation',()=>{
 it('requires an explicit review before confirming and receipts success despite a later read failure',async()=>{render(<ProfessionalProfilePanel/>);await screen.findByRole('button',{name:'Confirm profile'});calls.read.mockRejectedValueOnce(new Error('Read unavailable'));fireEvent.click(screen.getByRole('button',{name:'Confirm profile'}));await waitFor(()=>expect(calls.confirm).toHaveBeenCalledOnce());expect(calls.review).toHaveBeenCalledWith(expect.objectContaining({title:'Confirm professional summary?'}));await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('Professional summary confirmed'));expect(screen.getByRole('button',{name:'Confirm profile'}).matches(':disabled')).toBe(true);});
 it('reviews extraction as editable work-relevant text without auto-saving or confirming',async()=>{calls.private.mockResolvedValue({documents:[{id:'pdf',original_filename:'PDS.pdf',processing_status:'completed'}]});calls.draft.mockResolvedValue({draft:{...values,skills:['Extracted skill']}});render(<ProfessionalProfilePanel/>);await screen.findByRole('button',{name:'Review extracted draft'});fireEvent.click(screen.getByRole('button',{name:'Review extracted draft'}));await screen.findByLabelText('Skills');expect((screen.getByLabelText('Skills') as HTMLTextAreaElement).value).toBe('Extracted skill');expect(calls.update).not.toHaveBeenCalled();expect(calls.confirm).not.toHaveBeenCalled();expect(screen.getByText(/Saving resets earlier confirmation/)).toBeTruthy();});
 it('rejects empty or oversized PDFs before any upload call',async()=>{render(<ProfessionalProfilePanel/>);const upload=await screen.findByLabelText('Upload your PDS PDF');fireEvent.change(upload,{target:{files:[new File([], 'empty.pdf',{type:'application/pdf'})]}});expect(screen.getByRole('alert').textContent).toContain('nonempty PDF');expect(calls.upload).not.toHaveBeenCalled();});
});
