import { beforeEach, describe, expect, it, vi } from 'vitest';
const calls=vi.hoisted(()=>({offices:vi.fn(),reads:{} as Record<string,any>}));
vi.mock('../../src/lib/supabase',()=>({supabase:{from:(table:string)=>({select:()=>({eq:()=>({maybeSingle:async()=>calls.reads[table]})})})}}));
vi.mock('../../src/app/features/project-offices/services/projectOfficeService',()=>({fetchProjectOffices:calls.offices}));
import { readStaffingAuthority } from '../../src/app/features/project-offices/services/staffingAuthority';
beforeEach(()=>{vi.clearAllMocks();calls.offices.mockResolvedValue({offices:[{id:'participation',office_id:'own',project_id:'project',relationship_type:'collaborating',invitation_status:'joined'}],members:[{project_office_id:'participation',user_id:'m'}]});calls.reads={projects:{data:{status:'planning'},error:null},organizations:{data:{head_user_id:'head'},error:null},profiles:{data:{role:'head',is_active:true,org_id:'own'},error:null}};});
describe('Phase 14 checked staffing reads',()=>{
 it('returns current membership only after checked own-Head and project reads',async()=>{expect(await readStaffingAuthority('project','participation','head')).toEqual(['m']);});
 it('denies stale Head appointment, actor inactivity and cross-Office identity',async()=>{for(const patch of [{role:'member'},{role:'accounting_staff'},{role:'admin'},{is_active:false},{org_id:'foreign'}]){calls.reads.profiles.data={role:'head',is_active:true,org_id:'own',...patch};await expect(readStaffingAuthority('project','participation','head')).rejects.toThrow('current appointed Head');}calls.reads.profiles.data={role:'head',is_active:true,org_id:'own'};calls.reads.organizations.data.head_user_id='other';await expect(readStaffingAuthority('project','participation','head')).rejects.toThrow('current appointed Head');});
 it('propagates source failure and denies closed/governed projects',async()=>{calls.reads.projects.error={message:'Project read denied'};await expect(readStaffingAuthority('project','participation','head')).rejects.toThrow('Project read denied');calls.reads.projects.error=null;for(const data of [{status:'completed'},{status:'archived'},{status:'planning',source_collaboration_draft_id:'draft'}]){calls.reads.projects.data=data;await expect(readStaffingAuthority('project','participation','head')).rejects.toThrow('closed or governed');}});
 it('does not permit missing, pending, revoked or observer participation',async()=>{calls.offices.mockResolvedValue({offices:[],members:[]});await expect(readStaffingAuthority('project','participation','head')).rejects.toThrow('no longer available');for(const patch of [{invitation_status:'pending'},{invitation_status:'revoked'},{relationship_type:'observer'}]){calls.offices.mockResolvedValue({offices:[{id:'participation',office_id:'own',project_id:'project',relationship_type:'collaborating',invitation_status:'joined',...patch}],members:[]});await expect(readStaffingAuthority('project','participation','head')).rejects.toThrow('joined, non-observer');}});
});
