import {accessEnd} from '../../../shared/accessTerms';
import {useEffect,useRef,useState} from 'react';
import {useAuth} from '../../../contexts/AuthContext';
import {useExplicitDraft} from '../../../shared/useExplicitDraft';
import {useConfirmation} from '../../../components/ui/useConfirmation';
import {fetchAccess,grantAccess,revokeViewer,shareUrl,ACCESS_CHANGED_EVENT} from '../services/accessService';
import {RemovalDialog} from './RemovalDialog';
import type {AccessSnapshot,AccessPermission,Engagement,AccessGrant} from '../types';
import '../projectAccess.css';
export function ProjectAccessPanel({project,onChange}:{project:string;onChange?:()=>void|Promise<void>}){const {user}=useAuth();return <AccessContent key={`${user?.id}:${project}`} project={project} onChange={onChange}/>;}
function AccessContent({project,onChange}:{project:string;onChange?:()=>void|Promise<void>}){
 const [data,setData]=useState<AccessSnapshot>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[access,setAccess]=useState<AccessPermission>('viewer'),[engagement,setEngagement]=useState<Engagement>('Permanent'),[end,setEnd]=useState(''),[close,setClose]=useState(true),[ttl,setTtl]=useState(7),[receipt,setReceipt]=useState<AccessGrant>(),[removing,setRemoving]=useState<AccessGrant>();
 const request=useRef<string | undefined>(undefined),pending=useRef(false),active=useRef(true),generation=useRef(0),hold=useRef(false);hold.current=busy||Boolean(email)||Boolean(removing);const confirmation=useConfirmation();
 const guard=useExplicitDraft('Project sharing',Boolean(email)&&!receipt,busy,()=>{setEmail('');request.current=undefined;});
 async function reload(){const token=++generation.current;try{const next=await fetchAccess(project);if(active.current&&token===generation.current){setData(next);setError('');}}catch(reason){if(active.current&&token===generation.current){setData(undefined);setError((reason as Error).message);}}}
 useEffect(()=>{active.current=true;void reload();const refresh=()=>{if(!hold.current)void reload();};const interval=setInterval(refresh,15000);window.addEventListener('focus',refresh);window.addEventListener(ACCESS_CHANGED_EVENT,refresh);return()=>{active.current=false;generation.current++;clearInterval(interval);window.removeEventListener('focus',refresh);window.removeEventListener(ACCESS_CHANGED_EVENT,refresh);};},[project]);
 async function submit(){if(pending.current||!data?.can_share||!data.open)return;pending.current=true;setBusy(true);setError('');request.current??=crypto.randomUUID();try{const saved=await grantAccess(request.current,project,email.trim(),access,engagement,accessEnd(end,data.timezone||'Asia/Singapore'),close,ttl);setReceipt(saved);guard.markClean();await reload();await onChange?.();}catch(reason){setError((reason as Error).message);}finally{pending.current=false;setBusy(false);}}
 async function revoke(item:AccessGrant){if(pending.current)return;if(!await confirmation.confirm({title:`Revoke ${item.redeemed_at?'Viewer access':'share offer'} for ${item.name}?`,description:'This share will stop granting read access. Independent memberships remain effective.',actionLabel:'Revoke Viewer',danger:true}))return;pending.current=true;setBusy(true);try{await revokeViewer(item.id);await reload();await onChange?.();}catch(reason){setError((reason as Error).message);}finally{pending.current=false;setBusy(false);}}
 return <section className="r9-access" aria-label="Project sharing"><h3>Project sharing</h3><p>New Viewer access ends at its stated date or project close. Viewer reads permitted project content. Project members may execute assigned work and delegate only their appointed branch. Neither permission grants Head, review or finance authority. External onboarding uses Invitations.</p>
 {error&&<p role="alert">{error}<button type="button" disabled={busy} onClick={()=>void reload()}>Refresh sharing</button></p>}{data&&!data.can_share&&<p>Sharing is managed by the appointed Lead Office Head or personal workspace owner; personal external offers require the designated sponsoring Head.</p>}{data?.kind==='personal'&&data.can_share&&<p>For external personal sharing, give the sponsoring Head this <a href={`/manage-project-share?project=${encodeURIComponent(project)}`}>issuer link</a>. It grants no project membership or general read access.</p>}{data&&!data.open&&<p>Closed projects accept no new grants. Permanent access retains permitted read history; temporary access requires fresh approval after restoration.</p>}
 {data?.can_share&&data.open&&!receipt&&<form onSubmit={e=>{e.preventDefault();e.stopPropagation();void submit();}}><label>Existing verified recipient email<input type="email" required value={email} disabled={busy||!!request.current} onChange={e=>setEmail(e.target.value)}/></label><label>Project permission<select value={access} disabled={busy||!!request.current} onChange={e=>setAccess(e.target.value as AccessPermission)}><option value="viewer">Viewer · read only</option><option value="member">Project member · assigned work</option></select></label><label>Engagement<select value={engagement} disabled={busy||!!request.current} onChange={e=>setEngagement(e.target.value as Engagement)}>{['Permanent','Job Order','OJT','Consultant','Other'].map(value=><option key={value}>{value}</option>)}</select></label><label>Access ends after this date · {data.timezone||'Asia/Singapore'}<input type="date" value={end} disabled={busy||!!request.current} onChange={e=>setEnd(e.target.value)}/></label><label>Share redemption lifetime (days)<input type="number" min="1" max="30" value={ttl} disabled={busy||!!request.current} onChange={e=>setTtl(Number(e.target.value))}/></label><label className="r9-check"><input type="checkbox" checked={close} disabled={busy||!!request.current} onChange={e=>setClose(e.target.checked)}/>Until project completion or archive</label><button type="submit" disabled={busy||!email.trim()||engagement!=='Permanent'&&!end&&!close}>Create share offer</button></form>}
 {receipt&&<div role="status"><p>Share offer created for {receipt.email||email}. Copy this recipient-bound link; it requires their verified sign-in before {new Date(receipt.redeem_expires_at).toLocaleString('en-GB',{timeZone:data?.timezone||'Asia/Singapore'})}. Existing independent editing rights remain effective.</p><label>Recipient project link<input readOnly value={shareUrl(receipt.id)} onFocus={e=>e.target.select()}/></label><button type="button" onClick={()=>{setReceipt(undefined);setEmail('');request.current=undefined;}}>Share with another person</button></div>}
 <ul>{data?.grants.map(item=><li key={item.id}><strong>{item.name}</strong> · {item.access==='viewer'?'Viewer':'Project member'} · {item.engagement} · {item.effective?'Effective':!item.revoked_at&&!item.redeemed_at&&new Date(item.redeem_expires_at).getTime()>Date.now()?'Pending recipient redemption':'Expired / revoked / ended'}{item.access_end&&<span> · Ends {new Date(item.access_end).toISOString()}</span>}{item.until_close&&<span> · Until project closes</span>}{item.can_revoke&&!item.revoked_at&&(item.access==='viewer'||!item.redeemed_at?<button type="button" disabled={busy} onClick={()=>void revoke(item)}>{item.redeemed_at?'Revoke Viewer':'Revoke offer'} · {item.name}</button>:<button type="button" disabled={busy} onClick={()=>setRemoving(item)}>Review removal · {item.name}</button>)}</li>)}</ul>
 {removing&&<RemovalDialog project={project} user={removing.recipient} office={removing.office_id} name={removing.name} onClose={()=>setRemoving(undefined)} onRemoved={async()=>{await reload();await onChange?.();}}/>}{confirmation.dialog}</section>;
}
